---
permalink: swift/put-container-consistency-request.html 
sidebar: sidebar 
keywords: put container consistency request 
summary: 「放置容器一致性要求」可讓您指定要套用至容器上執行之作業的一致性。根據預設、會使用「新寫入後讀取」一致性來建立新的容器。 
---
= 放置容器一致性要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「放置容器一致性要求」可讓您指定要套用至容器上執行之作業的一致性。根據預設、會使用「新寫入後讀取」一致性來建立新的容器。



== 申請

[cols="2a,4a"]
|===
| 要求HTTP標頭 | 說明 


| X-AUTH-Token  a| 
用於要求的帳戶Swift驗證權杖。



| X-ntap-sg- 一致性  a| 
適用於容器上作業的一致性。支援下列值：

* 全部 * ：所有節點都會立即接收資料、否則要求將會失敗。

*Strong-globall* ：保證所有網站上所有用戶端要求的寫入後讀取一致性。

*Strong-site* ：保證網站內所有用戶端要求的寫入後讀取一致性。

* 新寫入後讀取 * ：（預設）提供新物件的寫入後讀取一致性、以及物件更新的最終一致性。提供高可用度與資料保護保證。建議大多數情況下使用。

* 可用 * ：提供新物件和物件更新的最終一致性。對於 S3 貯體、請僅視需要使用（例如、包含很少讀取的記錄值之貯體、或用於對不存在的金鑰執行 head 或 Get 作業）。S3 FabricPool 儲存區不支援。



| 主機  a| 
要求導向的主機名稱。

|===


== 一致性與 ILM 規則如何互動、以影響資料保護

您選擇的一致性和 ILM 規則都會影響物件的保護方式。這些設定可以互動。

例如、儲存物件時所使用的一致性會影響物件中繼資料的初始放置位置、而為 ILM 規則選取的擷取行為則會影響物件複本的初始放置位置。由於 StorageGRID 需要同時存取物件的中繼資料及其資料、才能滿足用戶端要求、因此針對一致性和擷取行為選擇符合的保護層級、可以提供更好的初始資料保護、以及更可預測的系統回應。

下列擷取行為適用於ILM規則：

* *嚴格*：ILM規則中指定的所有複本都必須在成功傳回用戶端之前完成。
* *平衡*：StorageGRID 在擷取時、會嘗試製作ILM規則中指定的所有複本；如果不可能、則會製作過渡複本、並將成功傳回給用戶端。ILM規則中指定的複本會盡可能製作。
* *雙重承諾*：StorageGRID 此物件立即製作過渡複本、並讓用戶端恢復成功。在ILM規則中指定的複本會盡可能製作。



NOTE: 在選擇ILM規則的擷取行為之前、請先閱讀資訊生命週期管理物件管理說明中有關這些設定的完整說明。



== 一致性與 ILM 規則互動方式的範例

假設您有一個雙站台網格、其中包含下列 ILM 規則及下列一致性：

* * ILM規則*：建立兩個物件複本、一個在本機站台、一個在遠端站台。選取嚴格的擷取行為。
* ** ：「 Strong-global" （物件中繼資料會立即發佈至所有站台。）


當用戶端將物件儲存到網格時、StorageGRID 在成功傳回用戶端之前、功能區會同時複製物件並將中繼資料散佈到兩個站台。

在擷取最成功的訊息時、物件會受到完整保護、不會遺失。例如、如果在擷取後不久即遺失本機站台、則物件資料和物件中繼資料的複本仍存在於遠端站台。物件可完全擷取。

如果您改用相同的 ILM 規則和「強式站台」一致性、則在物件資料複寫到遠端站台、但在物件中繼資料散佈到遠端站台之前、用戶端可能會收到成功訊息。在此情況下、物件中繼資料的保護層級與物件資料的保護層級不符。如果在擷取後不久本機站台便會遺失、則物件中繼資料將會遺失。無法擷取物件。

一致性與 ILM 規則之間的相互關係可能很複雜。如需協助、請聯絡NetApp。



== 申請範例

[listing]
----
PUT /v1/28544923908243208806/_Swift container_
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: strong-site
Host: test.com
----


== 回應

|===
| 回應HTTP標頭 | 說明 


 a| 
`Date`
 a| 
回應的日期和時間。



 a| 
`Connection`
 a| 
是否開啟或關閉與伺服器的連線。



 a| 
`X-Trans-Id`
 a| 
要求的唯一交易識別碼。



 a| 
`Content-Length`
 a| 
回應本文的長度。

|===


== 回應範例

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
----