= 尋找儲存節點的主機名稱
:allow-uri-read: 




== 尋找儲存節點的主機名稱

. 登入主要管理節點：
+
.. 輸入下列命令： `ssh admin@_primary_Admin_Node_IP_`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：
.. 輸入下列命令以切換至root： `su -`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：
+
當您以root登入時、提示會從變更 `$` 至 `#`。



. 使用 `/etc/hosts` 檔案以尋找已還原儲存磁碟區的儲存節點主機名稱。若要查看網格中所有節點的清單、請輸入下列命令： `cat /etc/hosts`。




== 如果所有磁碟區都失敗、請修復資料

如果所有儲存磁碟區都發生故障、請修復整個節點。根據您使用的是複寫資料、銷毀編碼（EC）資料、或兩者、請遵循*複寫資料*、*銷毀編碼（EC）資料*的指示。

如果只有部分磁碟區發生故障、請前往 <<如果只有部分磁碟區發生故障、請修復資料>>。


NOTE: 您無法執行 `repair-data` 同時執行多個節點的作業。若要恢復多個節點、請聯絡技術支援部門。

[role="tabbed-block"]
====
.複寫資料
--
如果您的網格包含複寫資料、請使用 `repair-data start-replicated-node-repair` 命令 `--nodes` 選項、其中 `--nodes` 是用來修復整個儲存節點的主機名稱（系統名稱）。

此命令可修復名為SG-DC-SN3之儲存節點上的複寫資料：

`repair-data start-replicated-node-repair --nodes SG-DC-SN3`


NOTE: 物件資料還原時、如果 StorageGRID 系統找不到複寫的物件資料、就會觸發 * 物件遺失 * 警示。警示可能會在整個系統的儲存節點上觸發。您應該判斷遺失原因、以及是否有可能恢復。請參閱 link:../troubleshoot/investigating-lost-objects.html["調查遺失的物件"]。

--
.銷毀編碼（ EC ）資料
--
如果您的網格包含銷毀編碼資料、請使用 `repair-data start-ec-node-repair` 命令 `--nodes` 選項、其中 `--nodes` 是用來修復整個儲存節點的主機名稱（系統名稱）。

此命令可修復名為SG-DC-SN3之儲存節點上的銷毀編碼資料：

`repair-data start-ec-node-repair --nodes SG-DC-SN3`

作業會傳回唯一的 `repair ID` 以識別這一點 `repair_data` 營運。請使用這項功能 `repair ID` 以追蹤的進度和結果 `repair_data` 營運。恢復程序完成時、不會傳回其他意見反應。


NOTE: 在某些儲存節點離線時、可以開始修復以銷毀編碼的資料。所有節點都可用後、修復作業即告完成。

--
====


== 如果只有部分磁碟區發生故障、請修復資料

如果只有部分磁碟區發生故障、請修復受影響的磁碟區。根據您使用的是複寫資料、銷毀編碼（EC）資料、或兩者、請遵循*複寫資料*、*銷毀編碼（EC）資料*的指示。

如果所有磁碟區都失敗、請前往 <<如果所有磁碟區都失敗、請修復資料>>。

以十六進位格式輸入Volume ID。例如、 `0000` 是第一個Volume和 `000F` 為第16個Volume。您可以指定一個 Volume 、一個 Volume 範圍或多個非連續的 Volume 。

所有磁碟區都必須位於同一個儲存節點上。如果您需要還原多個儲存節點的磁碟區、請聯絡技術支援部門。

[role="tabbed-block"]
====
.複寫資料
--
如果您的網格包含複寫資料、請使用 `start-replicated-volume-repair` 命令 `--nodes` 用於識別節點的選項（其中 `--nodes` 為節點的主機名稱）。然後新增任一項 `--volumes` 或 `--volume-range` 選項、如下列範例所示。

*單一磁碟區*：此命令可將複寫的資料還原至磁碟區 `0002` 在名為SG-DC-SN3的儲存節點上：

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0002`

*磁碟區範圍*：此命令可將複寫的資料還原至範圍內的所有磁碟區 `0003` 至 `0009` 在名為SG-DC-SN3的儲存節點上：

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*多個磁碟區未依序*：此命令可將複寫的資料還原至磁碟區 `0001`、 `0005`和 `0008` 在名為SG-DC-SN3的儲存節點上：

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0001,0005,0008`


NOTE: 物件資料還原時、如果 StorageGRID 系統找不到複寫的物件資料、就會觸發 * 物件遺失 * 警示。警示可能會在整個系統的儲存節點上觸發。請記下警示說明和建議的動作、以判斷遺失的原因、以及是否可能進行恢復。

--
.銷毀編碼（ EC ）資料
--
如果您的網格包含銷毀編碼資料、請使用 `start-ec-volume-repair` 命令 `--nodes` 用於識別節點的選項（其中 `--nodes` 為節點的主機名稱）。然後新增任一項 `--volumes` 或 `--volume-range` 選項、如下列範例所示。

* 單一 Volume * ：此命令可將刪除編碼的資料還原至 Volume `0007` 在名為SG-DC-SN3的儲存節點上：

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 0007`

* 磁碟區範圍 * ：此命令可將刪除編碼的資料還原至範圍內的所有磁碟區 `0004` 至 `0006` 在名為SG-DC-SN3的儲存節點上：

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

* 不按順序排列的多個磁碟區 * ：此命令可將刪除編碼的資料還原至磁碟區 `000A`、 `000C`和 `000E` 在名為SG-DC-SN3的儲存節點上：

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 000A,000C,000E`

。 `repair-data` 作業會傳回唯一的 `repair ID` 以識別這一點 `repair_data` 營運。請使用這項功能 `repair ID` 以追蹤的進度和結果 `repair_data` 營運。恢復程序完成時、不會傳回其他意見反應。


NOTE: 在某些儲存節點離線時、可以開始修復以銷毀編碼的資料。所有節點都可用後、修復作業即告完成。

--
====