---
permalink: tenant/configuration-xml-for-search-configuration.html 
sidebar: sidebar 
keywords: search integration, configuration xml, metadata notification, container tag, urn 
summary: 搜尋整合服務是使用<Metadata NotifyationConfiguration及</Metadata NotifyationConfiguration >標記中包含的一組規則來設定。每個規則都會指定規則適用的物件、StorageGRID 以及應將這些物件中繼資料傳送到哪個目的地。 
---
= 搜尋整合的組態XML
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
搜尋整合服務是使用中包含的一組規則來設定 `<MetadataNotificationConfiguration>` 和 `</MetadataNotificationConfiguration>` 標記。每個規則都會指定規則適用的物件、StorageGRID 以及應將這些物件中繼資料傳送到哪個目的地。

物件可依物件名稱的前置詞進行篩選。例如、您可以傳送具有前置碼之物件的中繼資料 `images` 至一個目的地、以及具有前置碼之物件的中繼資料 `videos` 到另一個。有重疊前置字元的組態無效、提交時會遭到拒絕。例如、含有一個前置字元物件規則的組態 `test` 和第二個規則、用於具有前置碼的物件 `test2` 不允許。

目的地必須使用StorageGRID 已為搜尋整合服務建立的一個端點的URN來指定。這些端點是指在ElasticSearch叢集上定義的索引和類型。

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
下表說明中繼資料通知組態XML中的元素。

[cols="2a,3a,1a"]
|===
| 名稱 | 說明 | 必要 


 a| 
Metadata NotifyationConfiguration
 a| 
用於指定中繼資料通知物件和目的地之規則的容器標籤。

包含一或多個規則元素。
 a| 
是的



 a| 
規則
 a| 
規則的容器標記、用於識別應將中繼資料新增至指定索引的物件。

會拒絕具有重疊前置碼的規則。

包括在Metadata NotifyationConfiguration元素中。
 a| 
是的



 a| 
ID
 a| 
規則的唯一識別碼。

包含在Rule元素中。
 a| 
否



 a| 
狀態
 a| 
狀態可以是「已啟用」或「已停用」。不針對停用的規則採取任何行動。

包含在Rule元素中。
 a| 
是的



 a| 
前置碼
 a| 
符合前置碼的物件會受到規則影響、其中繼資料會傳送到指定的目的地。

若要符合所有物件、請指定一個空白首碼。

包含在Rule元素中。
 a| 
是的



 a| 
目的地
 a| 
規則目的地的容器標記。

包含在Rule元素中。
 a| 
是的



 a| 
urn
 a| 
傳送物件中繼資料的目的地之一。必須是StorageGRID 具有下列屬性的不景端點的URN：

* `es` 必須是第三個元素。
* URN必須以索引結尾、並在表單中輸入中繼資料的儲存位置 `domain-name/myindex/mytype`。


端點是使用租戶管理程式或租戶管理API來設定。它們採用下列形式：

* `arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


端點必須在提交組態XML之前進行設定、否則組態將會失敗並顯示404錯誤。

目標元素中包含urn.
 a| 
是的

|===
使用範例中繼資料通知組態XML來瞭解如何建構您自己的XML。



== 適用於所有物件的中繼資料通知組態

在此範例中、所有物件的物件中繼資料都會傳送到相同的目的地。

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix></Prefix>
        <Destination>
           <Urn>urn:myes:es:::sgws-notifications/test1/all</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----


== 中繼資料通知組態有兩條規則

在此範例中、物件的中繼資料會與前置詞相符 `/images` 會傳送至一個目的地、而物件中繼資料則會與前置詞相符 `/videos` 傳送至第二個目的地。

[listing]
----

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Images-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/images</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/es-domain/graphics/imagetype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Videos-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/videos</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-west-1:22222222:domain/es-domain/graphics/videotype</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.相關資訊
link:../s3/index.html["使用S3 REST API"]

link:object-metadata-included-in-metadata-notifications.html["中繼資料通知中包含的物件中繼資料"]

link:json-generated-by-search-integration-service.html["由搜尋整合服務產生的JSON"]

link:configuring-search-integration-service.html["設定搜尋整合服務"]
