---
permalink: tenant/creating-s3-bucket.html 
sidebar: sidebar 
keywords: how to create S3 bucket 
summary: 您可以使用租戶管理程式來建立S3儲存區以供物件資料使用。 
---
= 建立S3儲存區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用租戶管理程式來建立S3儲存區以供物件資料使用。

.開始之前
* 您將使用登入租戶管理程式 link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您屬於具有「根目錄」存取權或「管理所有儲存區」的使用者群組 link:tenant-management-permissions.html["權限"]。這些權限會覆寫群組或儲存區原則中的權限設定。
+

NOTE: 可以授予設定或修改區段或物件之S3物件鎖定內容的權限 link:../s3/bucket-and-group-access-policies.html["庫位原則或群組原則"]。

* 如果您計畫為貯體啟用 S3 物件鎖定、則網格管理員已為 StorageGRID 系統啟用全域 S3 物件鎖定設定、而且您已檢閱 S3 物件鎖定貯體和物件的需求。請參閱 link:using-s3-object-lock.html["使用 S3 物件鎖定來保留物件"]。




== 存取精靈

.步驟
. 從儀表板選取 * 檢視貯體 * 、或選取 * 儲存空間（ S3 ） * > * 鏟斗 * 。
. 選取*建立桶*。




== 輸入詳細資料

.步驟
. 輸入貯體的詳細資料。
+
[cols="1a,3a"]
|===
| 欄位 | 說明 


 a| 
儲存區名稱
 a| 
符合以下規則的貯體名稱：

** 必須在各個StorageGRID 方面都是獨一無二的（不只是租戶帳戶內的獨特功能）。
** 必須符合DNS規範。
** 必須包含至少3個字元、且不得超過63個字元。
** 每個標籤都必須以英文字母或數字開頭和結尾、而且只能使用英文字母、數字和連字號。
** 不應在虛擬託管樣式要求中使用期間。期間會導致伺服器萬用字元憑證驗證發生問題。


如需詳細資訊、請參閱 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Amazon Web Services（AWS）儲存區命名規則文件"^]。

* 附註 * ：建立貯體後、您無法變更貯體名稱。



 a| 
區域
 a| 
貯體的區域。

您的系統管理員負責管理可用的區域。StorageGRID儲存區的區域可能會影響套用至物件的資料保護原則。依預設、所有的儲存區都會在中建立 `us-east-1` 區域。

* 附註 * ：建立貯體後、您無法變更區域。

|===
. 選擇*繼續*。




== 管理物件設定

.步驟
. 或者、為儲存區啟用物件版本管理。
+
如果您要儲存此儲存區中每個物件的每個版本、請啟用物件版本管理。然後您可以視需要擷取物件的舊版。如果儲存區將用於跨網格複寫、則必須啟用物件版本管理。

. 如果啟用全域 S3 物件鎖定設定、則可選擇性啟用儲存區的 S3 物件鎖定、以使用一次寫入多讀（ WORM ）模式來儲存物件。
+
只有當您需要保留物件一段固定時間（例如、為了符合特定法規要求）時、才需要為貯體啟用 S3 物件鎖定。S3 物件鎖定是一項永久性設定、可協助您防止物件在固定的時間內或無限期地遭到刪除或覆寫。

+

CAUTION: 為貯體啟用 S3 物件鎖定設定之後、就無法停用該設定。擁有正確權限的任何人都可以將無法變更的物件新增至此貯體。您可能無法刪除這些物件或貯體本身。

+
如果您為儲存區啟用S3物件鎖定、則會自動啟用儲存區版本設定。

. 如果您選取 * 啟用 S3 物件鎖定 * 、則可選擇性啟用此貯體的 * 預設保留 * 。
+
啟用 * 預設保留 * 時、新增至貯體的新物件將會自動受到保護、不被刪除或覆寫。「 * 預設保留 * 」設定不會套用至具有其本身保留期間的物件。

+
.. 如果啟用 * 預設保留 * 、請為貯體指定 * 預設保留模式 * 。
+
[cols="1a,2a"]
|===
| 預設保留模式 | 說明 


 a| 
法規遵循
 a| 
*** 直到達到物件的保留日期、才能刪除物件。
*** 物件的保留日期可以增加、但不能減少。
*** 直到達到該日期為止、才能移除物件的保留日期。




 a| 
治理
 a| 
*** 的使用者 `s3:BypassGovernanceRetention` 權限可以使用 `x-amz-bypass-governance-retention: true` 要求標頭略過保留設定。
*** 這些使用者可以在達到物件版本的保留截止日期之前刪除物件版本。
*** 這些使用者可以增加、減少或移除物件的保留到目前為止。


|===
.. 如果啟用 * 預設保留 * 、請指定貯體的 * 預設保留期間 * 。
+
「 * 預設保留期間 * 」表示新增至此貯體的物件應保留多久、從擷取開始算起。指定 1 至 36500 天或 1 至 100 年（含）之間的值。



. 選取*建立桶*。
+
此庫位會建立並新增至「庫位」頁面上的表格。

. 您也可以選擇 * 前往儲存庫詳細資料頁面 * link:viewing-s3-bucket-details.html["檢視貯體詳細資料"] 並執行其他組態。

