---
permalink: tenant/using-storagegrid-tenant-account.html 
sidebar: sidebar 
keywords: how to use tenant account 
summary: 租戶帳戶可讓您使用簡易儲存服務（S3）REST API或Swift REST API、在StorageGRID 一個無法恢復的系統中儲存及擷取物件。 
---
= 使用StorageGRID 綁定帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
租戶帳戶可讓您使用簡易儲存服務（S3）REST API或Swift REST API、在StorageGRID 一個無法恢復的系統中儲存及擷取物件。

每個租戶帳戶都有自己的聯盟或本機群組、使用者、S3儲存區或Swift容器、以及物件。

或者、租戶帳戶可用來分隔不同實體所儲存的物件。例如、多個租戶帳戶可用於下列任一使用案例：

* *企業使用案例：* StorageGRID 如果在企業內部使用此功能、則網格的物件儲存設備可能會由組織內的不同部門加以分隔。例如、行銷部門、客戶支援部門、人力資源部門等可能有租戶帳戶。
+

NOTE: 如果您使用S3用戶端傳輸協定、也可以使用S3儲存區和儲存區原則來分隔企業部門之間的物件。您不需要建立個別的租戶帳戶。請參閱實作說明 link:../s3/bucket-and-group-access-policies.html["S3 貯體和貯體原則"] 以取得更多資訊。

* *服務供應商使用案例：* StorageGRID 如果服務供應商正在使用此功能、則網格的物件儲存設備可能會由租用儲存設備的不同實體加以分隔。例如、公司A、公司B、公司C等可能有租戶帳戶。




== 建立租戶帳戶

租戶帳戶是StorageGRID 由使用Grid Manager的資料網格管理員所建立。建立租戶帳戶時、網格管理員會指定下列資訊：

* 租戶的顯示名稱（租戶的帳戶 ID 會自動指派、無法變更）。
* 租戶帳戶是否會使用S3或Swift。
* 對於S3租戶帳戶：是否允許租戶帳戶使用平台服務。如果允許使用平台服務、則必須設定網格以支援其使用。
* 或者、租戶帳戶的儲存配額、也就是租戶物件可用的GB、TB或PB上限。租戶的儲存配額代表邏輯容量（物件大小）、而非實體容量（磁碟大小）。
* 如果啟用StorageGRID 身分識別聯盟以供支援整個系統、則哪個聯盟群組具有root存取權限、可設定租戶帳戶。
* 如果StorageGRID 不使用單一登入（SSO）進行支援、則租戶帳戶是使用自己的身分識別來源、還是共用網格的身分識別來源、以及租戶本機root使用者的初始密碼。


此外、如果StorageGRID S3租戶帳戶需要符合法規要求、網格管理員也可以針對該系統啟用S3物件鎖定設定。啟用S3物件鎖定時、所有S3租戶帳戶都能建立及管理相容的儲存區。



== 設定S3租戶

建立S3租戶帳戶之後、您可以存取租戶管理程式來執行下列工作：

* 設定身分識別聯盟（除非身分識別來源與網格共用）、或建立本機群組和使用者
* 管理S3存取金鑰
* 建立及管理S3儲存區、包括符合法規的儲存區
* 使用平台服務（若已啟用）
* 監控儲存使用量



TIP: 雖然您可以使用租戶管理程式來建立和管理S3儲存區、但您必須擁有S3存取金鑰、並使用S3 REST API來擷取和管理物件。



== 設定Swift租戶

建立 Swift 租戶帳戶之後、擁有「根」存取權限的使用者可以存取租戶管理員、以執行下列工作：

* 設定身分識別聯盟（除非身分識別來源與網格共用）、以及建立本機群組和使用者
* 監控儲存使用量



TIP: Swift使用者必須擁有root存取權限、才能存取租戶管理程式。不過、「根」存取權限不允許使用者驗證Swift REST API、以建立容器和擷取物件。使用者必須具有Swift Administrator權限、才能驗證到Swift REST API。

.相關資訊
link:../admin/index.html["管理StorageGRID"]

link:../s3/index.html["使用S3 REST API"]

link:../swift/index.html["使用Swift REST API"]
