---
permalink: admin/archive-node-configuration-and-operation.html 
sidebar: sidebar 
keywords: archive node configuration 
summary: 您的系統可將歸檔節點管理為永久儲存物件且隨時可供存取的位置。StorageGRID 
---
= 歸檔節點組態與作業
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您的系統可將歸檔節點管理為永久儲存物件且隨時可供存取的位置。StorageGRID

擷取物件時、會根據為 StorageGRID 系統定義的資訊生命週期管理（ ILM ）規則、將複本複製到所有必要位置、包括歸檔節點。歸檔節點可做為TSM伺服器的用戶端、而TSM用戶端程式庫則是StorageGRID 透過安裝此軟體的程序安裝在歸檔節點上。導向至歸檔節點以供儲存的物件資料會在收到時直接儲存至TSM伺服器。歸檔節點在將物件資料儲存至TSM伺服器之前、不會將其登入、也不會執行物件集合體。不過、如果資料傳輸率有保證、歸檔節點可以在單一交易中、將多個複本提交給TSM伺服器。

歸檔節點將物件資料儲存至TSM伺服器之後、物件資料會由TSM伺服器使用其生命週期/保留原則來管理。必須定義這些保留原則、才能與歸檔節點的作業相容。也就是、歸檔節點儲存的物件資料必須無限期儲存、而且歸檔節點必須隨時都能存取、除非歸檔節點將其刪除。

在不影響StorageGRID 整個系統的ILM規則與TSM伺服器的生命週期/保留原則之間沒有任何關聯。每個物件彼此獨立運作、但當每個物件被擷取到StorageGRID 這個系統時、您可以指派一個TSM管理類別給它。此管理類別會連同物件資料一起傳遞給TSM伺服器。將不同的管理類別指派給不同的物件類型、可讓您設定TSM伺服器、將物件資料放在不同的儲存資源池中、或視需要套用不同的移轉或保留原則。例如、識別為資料庫備份的物件（暫存內容無法以較新的資料覆寫）處理方式可能與應用程式資料（必須無限期保留的固定內容）不同。

歸檔節點可與新的或現有的TSM伺服器整合、不需要專用的TSM伺服器。TSM伺服器可與其他用戶端共用、前提是TSM伺服器的大小必須符合預期的最大負載。TSM必須安裝在與歸檔節點不同的伺服器或虛擬機器上。

您可以將多個歸檔節點設定為寫入同一個TSM伺服器、但只有在歸檔節點將不同的資料集寫入TSM伺服器時、才建議使用此組態。當每個歸檔節點將相同物件資料的複本寫入歸檔時、不建議將多個歸檔節點設定為寫入相同的TSM伺服器。在後一種情況下、這兩個複本都會受到單點故障（TSM伺服器）的影響、因為這兩個複本應該是獨立的物件資料備援複本。

歸檔節點不會使用 TSM 的階層式儲存管理（ HSM ）元件。
