---
permalink: admin/configuring-audit-client-access.html 
sidebar: sidebar 
keywords: audit client, ams, audit management service 
summary: 管理節點透過稽核管理系統（AMS）服務、將所有稽核的系統事件記錄到可透過稽核共用區取得的記錄檔中、稽核共用區會在安裝時新增至每個管理節點。稽核共用會自動啟用為唯讀共用。 
---
= 設定 NFS 的稽核用戶端存取
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理節點透過稽核管理系統（AMS）服務、將所有稽核的系統事件記錄到可透過稽核共用區取得的記錄檔中、稽核共用區會在安裝時新增至每個管理節點。稽核共用會自動啟用為唯讀共用。


NOTE: NFS 支援已過時、將於未來版本中移除。

若要存取稽核記錄、您可以設定用戶端存取來稽核 NFS 的共用。或者、您也可以 link:../monitor/considerations-for-external-syslog-server.html["使用外部 Syslog 伺服器"]。

此系統使用正面的認可、在稽核訊息寫入記錄檔之前、防止其遺失。StorageGRID在AMS服務或中繼稽核轉送服務已認可其控制權之前、訊息會一直排入服務佇列。如需詳細資訊、請參閱 link:../audit/index.html["檢閱稽核記錄"]。

.開始之前
* 您擁有 `Passwords.txt` 具有 root / admin 密碼的檔案。
* 您擁有 `Configuration.txt` 檔案（可在恢復套件中取得）。
* 稽核用戶端使用NFS版本3（NFSv3）。


.關於這項工作
針對StorageGRID 您要從中擷取稽核訊息的各個執行此程序、以利執行此程序。

.步驟
. 登入主要管理節點：
+
.. 輸入下列命令： `ssh admin@_primary_Admin_Node_IP_`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：
.. 輸入下列命令以切換至root： `su -`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：
+
當您以root登入時、提示會從變更 `$` 至 `#`。



. 確認所有服務的狀態均為「執行中」或「已驗證」。輸入： `storagegrid-status`
+
如果任何服務未列示為「執行中」或「已驗證」、請先解決問題再繼續。

. 返回命令列。按* Ctrl-*+* C*。
. 啟動NFS組態公用程式。輸入： `config_nfs.rb`
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. 新增稽核用戶端： `add-audit-share`
+
.. 出現提示時、輸入稽核共用區的稽核用戶端IP位址或IP位址範圍： `client_IP_address`
.. 出現提示時、請按* Enter *。


. 如果允許多個稽核用戶端存取稽核共用區、請新增其他使用者的IP位址： `add-ip-to-share`
+
.. 輸入稽核共用的數量： `_audit_share_number_`
.. 出現提示時、輸入稽核共用區的稽核用戶端IP位址或IP位址範圍： `_client_IP_address_`
.. 出現提示時、請按* Enter *。
+
隨即顯示NFS組態公用程式。

.. 針對每個具有稽核共用存取權的其他稽核用戶端重複這些子步驟。


. 或者、請驗證您的組態。
+
.. 輸入下列項目： `validate-config`
+
系統會檢查並顯示這些服務。

.. 出現提示時、請按* Enter *。
+
隨即顯示NFS組態公用程式。

.. 關閉NFS組態公用程式： `exit`


. 判斷您是否必須在其他站台啟用稽核共用。
+
** 如果StorageGRID 這個部署是單一站台、請前往下一步。
** 如果StorageGRID 此功能包括其他站台的管理節點、請視需要啟用這些稽核共用：
+
... 遠端登入站台的管理節點：
+
.... 輸入下列命令： `ssh admin@_grid_node_IP_`
.... 輸入中所列的密碼 `Passwords.txt` 檔案：
.... 輸入下列命令以切換至root： `su -`
.... 輸入中所列的密碼 `Passwords.txt` 檔案：


... 重複這些步驟、為每個額外的管理節點設定稽核共用。
... 關閉遠端安全Shell登入遠端管理節點。輸入： `exit`




. 登出命令Shell： `exit`
+
NFS稽核用戶端會根據其IP位址授予稽核共用的存取權。將稽核共用區的IP位址新增至共用區、將稽核共用區的存取權限授予新的NFS稽核用戶端、或移除現有的稽核用戶端IP位址、以移除該用戶端。


