---
permalink: admin/migrating-data-into-storagegrid.html 
sidebar: sidebar 
keywords: data migration, move data into storagegrid 
summary: 您可以將大量資料移轉至StorageGRID 整個過程、同時使用StorageGRID 本系統進行日常作業。 
---
= 將資料移轉StorageGRID 至功能不整合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將大量資料移轉至StorageGRID 整個過程、同時使用StorageGRID 本系統進行日常作業。

規劃將大量資料移轉至 StorageGRID 系統時、請使用本指南。這不是資料移轉的一般指南、也不包含執行移轉的詳細步驟。請遵循本節中的準則和指示、確保資料能有效率地移轉到StorageGRID 運轉不中斷日常作業的情況下、StorageGRID 且已移轉的資料會由效能提升系統妥善處理。



== 確認StorageGRID 該系統的容量

在將大量資料移轉到StorageGRID 整個過程之前、請先確認StorageGRID 該系統具備處理預期磁碟區的磁碟容量。

如果 StorageGRID 系統包含歸檔節點、且已將移轉物件的複本儲存至近線儲存設備（例如磁帶）、請確保歸檔節點的儲存設備有足夠容量可容納預期的移轉資料量。

在容量評估中、請查看您計畫移轉之物件的資料設定檔、並計算所需的磁碟容量。如需監控StorageGRID 您的作業系統磁碟容量的詳細資訊、請參閱 link:managing-storage-nodes.html["管理儲存節點"] 以及的指示 link:../monitor/index.html["監控 StorageGRID"]。



== 判斷移轉資料的ILM原則

這個系統的ILM原則決定了複本的製作量、複本的儲存位置、以及複本保留的時間長度。StorageGRIDILM原則包含一組ILM規則、說明如何篩選物件及管理物件資料。

視移轉資料的使用方式和移轉資料的需求而定、您可能會想要針對移轉資料定義不同於日常作業所用ILM規則的獨特ILM規則。例如、如果日常資料管理的法規要求與移轉所含資料的法規要求不同、您可能需要不同等級的儲存設備上不同數量的移轉資料複本。

您可以設定專屬套用至移轉資料的規則、以便在移轉資料與儲存自日常作業的物件資料之間進行唯一區分。

如果您可以使用其中一個中繼資料準則來可靠地區分資料類型、您可以使用此準則來定義僅適用於移轉資料的ILM規則。

在開始資料移轉之前、請先確認您已瞭解StorageGRID 完此系統的ILM原則、以及它將如何套用至移轉的資料、並已對ILM原則進行任何變更並進行測試。請參閱 link:../ilm/index.html["使用ILM管理物件"]。


CAUTION: 未正確指定的ILM原則可能導致無法恢復的資料遺失。在啟動ILM原則之前、請仔細檢閱您對其所做的所有變更、以確保原則能如預期運作。



== 評估移轉對營運的影響

支援物件儲存與擷取的功能設計可有效運作、並可無縫建立物件資料與中繼資料的備援複本、提供絕佳的資料遺失保護。StorageGRID

不過、資料移轉必須依照本指南的指示小心管理、以免影響日常系統作業、或是在極端情況下、在 StorageGRID 系統發生故障時、將資料置於遺失風險。

大量資料的移轉會對系統產生額外的負載。當系統負載很重時、它會更緩慢回應儲存和擷取物件的要求。StorageGRID這可能會干擾儲存區和擷取日常作業不可或缺的要求。移轉也可能導致其他作業問題。例如、當儲存節點即將達到容量時、由於批次擷取所造成的大量間歇性負載、可能會導致儲存節點在唯讀和讀寫之間循環、進而產生通知。

如果負載持續沉重、佇列就能開發出StorageGRID 各種作業、而這些作業必須由該系統執行、才能確保物件資料和中繼資料的完整備援。

資料移轉必須依照本文件中的準則仔細管理、以確保StorageGRID 在移轉過程中安全且有效率地操作此系統。移轉資料時、請以批次方式擷取物件、或持續限制擷取。然後、持續監控 StorageGRID 系統、確保不會超過各種屬性值。



== 排程及監控資料移轉

資料移轉必須排程並視需要進行監控、以確保資料是根據ILM原則在所需時間範圍內放置。



=== 排程資料移轉

避免在核心作業時間內移轉資料。將資料移轉限制在系統使用率偏低的晚上、週末和其他時間。

如果可能、請勿在活動頻繁期間排程資料移轉。然而、如果完全避免高活動期間是不實際的、只要您密切監控相關屬性、並在超出可接受的值時採取行動、就可以安全地繼續。



=== 監控資料移轉

下表列出資料移轉期間必須監控的屬性、以及它們所代表的問題。

如果您使用流量分類原則搭配速率限制來調節擷取速度、您可以搭配下表所述的統計資料來監控觀察的速率、並視需要減少限制。

[cols="1a,2a"]
|===
| 監控 | 說明 


 a| 
等待ILM評估的物件數目
 a| 
. 選取*支援*>*工具*>*網格拓撲*。
. 選擇「*部署_*>*總覽*>*主要*」。
. 在ILM活動區段中、監控下列屬性所顯示的物件數量：
+
** *等待-全部（XQUZ）*：等待ILM評估的物件總數。
** *等待-用戶端（XCQZ）*：等待用戶端作業（例如擷取）ILM評估的物件總數。


. 如果這些屬性中任一屬性所顯示的物件數量超過100、請節流物件的擷取速度、以減少StorageGRID 整個過程中的負載。




 a| 
目標歸檔系統的儲存容量
 a| 
如果ILM原則將移轉資料的複本儲存到目標歸檔儲存系統（磁帶或雲端）、請監控目標歸檔儲存系統的容量、以確保移轉資料有足夠的容量。



 a| 
*歸檔節點*>* ARC/>*儲存*
 a| 
如果觸發*儲存故障（ARVF*）*屬性的警示、則目標歸檔儲存系統可能已達到容量。檢查目標歸檔儲存系統、並解決觸發警示的任何問題。

|===