---
permalink: admin/storage-node-configuration-settings.html 
sidebar: sidebar 
keywords: storage node, configuration settings, counters 
summary: 每個儲存節點都使用數個組態設定和計數器。您可能需要檢視目前的設定或重設計數器、才能清除警示（舊系統）。 
---
= 儲存節點組態設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每個儲存節點都使用數個組態設定和計數器。您可能需要檢視目前的設定或重設計數器來清除警示（舊系統）。


CAUTION: 除非文件中有特別指示、否則在修改任何儲存節點組態設定之前、您應諮詢技術支援部門。您可以視需要重設事件計數器、以清除舊有的警示。

請依照下列步驟存取儲存節點的組態設定和計數器。

.步驟
. 選取*支援*>*工具*>*網格拓撲*。
. 選取「*站台_*>*儲存節點_*」。
. 展開儲存節點、然後選取服務或元件。
. 選取*組態*索引標籤。


下表摘要說明儲存節點組態設定。



== LdR

[cols="2a,1a,3a"]
|===
| 屬性名稱 | 程式碼 | 說明 


 a| 
HTTP 狀態
 a| 
HSTE
 a| 
S3 、 Swift 和其他內部 StorageGRID 流量的 HTTP 目前狀態：

* 離線：不允許任何作業、任何嘗試開啟HTTP工作階段至LMR服務的用戶端應用程式都會收到錯誤訊息。作用中工作階段會正常關閉。
* 線上：運作正常




 a| 
自動啟動HTTP
 a| 
HTAS
 a| 
* 如果選取此選項、系統重新啟動時的狀態取決於* LdR*>* Storage*元件的狀態。如果* LdR*>* Storage*元件在重新啟動時為唯讀、則HTTP介面也是唯讀的。如果「* LdR*>* Storage*元件」為「線上」、則HTTP也會顯示為「線上」。否則、HTTP介面會維持在離線狀態。
* 如果未選取、HTTP介面會保持離線狀態、直到明確啟用為止。


|===


== LDR >資料儲存區

[cols="2a,1a,3a"]
|===
| 屬性名稱 | 程式碼 | 說明 


 a| 
重設遺失物件數
 a| 
RCOR
 a| 
重設此服務上遺失物件數的計數器。

|===


== LMR >儲存設備

[cols="2a,1a,3a"]
|===
| 屬性名稱 | 程式碼 | 說明 


 a| 
Storage State（儲存狀態）-所需的
 a| 
SSD
 a| 
使用者可設定的儲存元件所需狀態設定。LDR服務會讀取此值、並嘗試符合此屬性所指示的狀態。此值會在重新啟動後持續顯示。

例如、您可以使用此設定強制儲存成為唯讀、即使有足夠的可用儲存空間也沒問題。這對疑難排解很有用。

屬性可以使用下列其中一個值：

* 離線：當所需的狀態為離線時、LMR服務會使* LdR*>* Storage*元件離線。
* 唯讀：當所需狀態為唯讀時、 LDR 服務會將儲存狀態移至唯讀、並停止接受新內容。不過、 LDR 服務仍會繼續接受 S3 或 ILM 導向的清除和刪除要求。請注意、在開啟的工作階段關閉之前、內容可能會繼續儲存至儲存節點一段短時間。
* 線上：正常系統作業期間、請將價值留在線上。儲存狀態（即儲存元件的目前狀態）將由服務根據LMR服務的條件（例如可用的物件儲存空間量）動態設定。如果空間不足、元件會變成唯讀。




 a| 
健全狀況檢查逾時
 a| 
SHCT
 a| 
健全狀況檢查測試必須完成的時間限制（以秒為單位）、儲存磁碟區才會被視為健全狀況。只有在「支援」指示時才變更此值。

|===


== LMR >驗證

[cols="2a,1a,3a"]
|===
| 屬性名稱 | 程式碼 | 說明 


 a| 
重設遺失的物件數
 a| 
VMI
 a| 
重設偵測到的遺失物件數（Ois）。僅在物件存在檢查完成後才使用。遺失的複寫物件資料會由StorageGRID 整個系統自動還原。



 a| 
驗證率
 a| 
VPRI
 a| 
設定背景驗證的執行速度。請參閱設定背景驗證率的相關資訊。



 a| 
重設毀損的物件數
 a| 
Vccr
 a| 
重設計數器、以找出在背景驗證期間找到的毀損複寫物件資料。此選項可用於清除偵測到的毀損物件（OCOR）警示條件。



 a| 
刪除隔離的物件
 a| 
OQRT
 a| 
從隔離目錄中刪除毀損的物件、將隔離物件的計數重設為零、然後清除「已偵測到隔離物件（OQRT）」警示。此選項會在作業系統自動還原毀損的物件之後使用StorageGRID 。

如果觸發「遺失物件」警示、技術支援人員可能會想要存取隔離的物件。在某些情況下、隔離的物件可能有助於資料還原或偵錯造成毀損物件複本的基礎問題。

|===


== LDR >銷毀編碼

[cols="2a,1a,3a"]
|===
| 屬性名稱 | 程式碼 | 說明 


 a| 
重設寫入失敗計數
 a| 
RSRWF-..
 a| 
重設計數器、將銷毀編碼物件資料的寫入失敗寫入儲存節點。



 a| 
重設讀取失敗計數
 a| 
RSRF
 a| 
重設計數器、以瞭解從儲存節點刪除編碼物件資料的讀取失敗情形。



 a| 
重設刪除失敗計數
 a| 
RSDF
 a| 
重設計數器、以刪除儲存節點中以銷毀編碼的物件資料失敗。



 a| 
重設偵測到毀損的複本計數
 a| 
RSCC
 a| 
重設計數器、以取得儲存節點上銷毀編碼物件資料的毀損複本數量。



 a| 
重設偵測到的毀損片段計數
 a| 
RCD
 a| 
重設儲存節點上的銷毀編碼物件資料毀損的片段計數器。



 a| 
重設偵測到的遺失片段計數
 a| 
RSMD..
 a| 
重設儲存節點上的銷毀編碼物件資料遺失片段計數器。僅在物件存在檢查完成後才使用。

|===


== LMR >複寫

[cols="2a,1a,3a"]
|===
| 屬性名稱 | 程式碼 | 說明 


 a| 
重設傳入複寫失敗計數
 a| 
RICR
 a| 
重設傳入複寫失敗的計數器。這可用來清除RIRF（傳入複寫-失敗）警示。



 a| 
重設傳出複寫失敗計數
 a| 
ROCR
 a| 
重設傳出複寫失敗的計數器。這可用來清除RORF（傳出複製-失敗）警示。



 a| 
停用傳入複寫
 a| 
DSIR
 a| 
選取以停用傳入複寫、作為維護或測試程序的一部分。在正常操作期間保持未核取狀態。

停用傳入複寫時、可從儲存節點擷取物件、以複製到 StorageGRID 系統中的其他位置、但無法從其他位置將物件複製到此儲存節點： LDR 服務為唯讀。



 a| 
停用輸出複寫
 a| 
DSOR
 a| 
選取以停用傳出複寫（包括HTTP擷取內容要求）、作為維護或測試程序的一部分。在正常操作期間保持未核取狀態。

停用輸出複寫時、物件可以複製到此儲存節點、但無法從儲存節點擷取物件、以複製到 StorageGRID 系統的其他位置。LDR服務為純寫入。

|===