---
permalink: admin/what-is-autosupport.html 
sidebar: sidebar 
keywords: autosupport, technical support, storagegrid health, system status, Active IQ 
summary: AutoSupport 功能可讓 StorageGRID 將健全狀況和狀態套件傳送至 NetApp 技術支援。 
---
= 使用 AutoSupport ：概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 功能可讓 StorageGRID 將健全狀況和狀態套件傳送至 NetApp 技術支援。

使用 AutoSupport 可以大幅加速問題的判斷與解決。技術支援也能監控系統的儲存需求、協助您判斷是否需要新增節點或站台。您也可以設定 AutoSupport 套件、將其傳送至其他目的地。

StorageGRID 有兩種類型的 AutoSupport ：

StorageGRID AutoSupport:: 回報 StorageGRID 軟體問題。在您第一次安裝 StorageGRID 時、預設為啟用。您可以 link:configure-autosupport-grid-manager.html["變更預設的 AutoSupport 組態"] 如有需要。



NOTE: 如果未啟用 StorageGRID AutoSupport 、則會在 Grid Manager 儀表板上顯示訊息。此訊息包含AutoSupport 指向「資訊功能」組態頁面的連結。如果您關閉訊息、它將不會再次出現、直到您的瀏覽器快取被清除為止、即使AutoSupport 停用的是停用的。

應用裝置硬體 AutoSupport:: 回報 StorageGRID 應用裝置問題。您必須 link:configure-autosupport-grid-manager.html#autosupport-for-appliances["在每個應用裝置上設定硬體 AutoSupport"]。




== 什麼是Active IQ 功能？

NetApp是雲端型數位顧問、運用NetApp安裝基礎上的預測分析和社群智慧。Active IQ其持續風險評估、預測性警示、說明性指引及自動化行動、可協助您在問題發生之前預防問題發生、進而改善系統健全狀況並提高系統可用度。

如果您想要在 NetApp 支援網站 上使用 Active IQ 儀表板和功能、您必須啟用 AutoSupport 。

https://docs.netapp.com/us-en/active-iq/index.html["Active IQ Digital Advisor 數位顧問文件"^]



== AutoSupport 套件中包含的資訊

AutoSupport 套件包含下列 XML 檔案和詳細資料。

[cols="2a,2a,3a"]
|===
| 檔案名稱 | 欄位 | 說明 


 a| 
AutoSupport 歷史記錄 .xml
 a| 
AutoSupport 序號 +
此 AutoSupport + 的目的地
觸發事件 +
交付狀態 +
交付嘗試 +
AutoSupport 主旨 +
傳遞 URI +
上次錯誤 +
AutoSupport Put Filename +
世代時代 +
AutoSupport 壓縮大小 +
AutoSupport 解壓縮大小 +
總收集時間（毫秒）
 a| 
AutoSupport 歷程檔案



 a| 
AutoSupport .xml
 a| 
節點 +
聯絡支援 + 的通訊協定
支援 HTTP/HTTPS + 的 URL
支援地址 +
AutoSupport 隨選狀態 +
AutoSupport 隨需伺服器 URL +
AutoSupport 隨需輪詢間隔
 a| 
AutoSupport 狀態檔案。提供使用的通訊協定、技術支援 URL 和位址、輪詢間隔、以及啟用或停用的隨選 AutoSupport 等詳細資料。



 a| 
buckets 。 xml
 a| 
貯體 ID +
帳戶 ID +
建置版本 +
位置限制組態 +
法規遵循已啟用 +
法規遵循組態 +
啟用 S3 物件鎖定 +
S3 物件鎖定組態 +
一致性組態 +
CORS 已啟用 +
CORS 組態 +
上次存取時間已啟用 +
原則已啟用 +
原則組態 +
通知已啟用 +
通知組態 +
Cloud Mirror 已啟用 +
Cloud Mirror 組態 +
啟用搜尋 +
搜尋組態 +
Swift 讀取 ACL 已啟用 +
Swift 讀取 ACL 組態 +
Swift Write ACL 已啟用 +
Swift Write ACL 組態 +
已啟用貯體標記 +
貯體標記組態 +
版本設定
 a| 
提供貯體層級的組態詳細資料和統計資料。貯體組態範例包括平台服務、法規遵循及貯體一致性。



 a| 
GRID 組態 .xml
 a| 
屬性 ID +
屬性名稱 +
價值 +
索引 +
表 ID +
表格名稱
 a| 
全網格組態資訊檔案。包含網格憑證、中繼資料保留空間、網格範圍組態設定（符合性、 S3 物件鎖定、物件壓縮、警示、系統記錄、 和 ILM 組態）、銷毀編碼設定檔詳細資料、 DNS 名稱、 link:../primer/nodes-and-services.html#storagegrid-services["NMS 名稱"]等等。



 a| 
GRE-SPEC.xml
 a| 
網格規格、原始 XML
 a| 
用於設定及部署 StorageGRID 。包含網格規格、 NTP 伺服器 IP 、 DNS 伺服器 IP 、網路拓撲和節點的硬體設定檔。



 a| 
GRID 工作 .xml
 a| 
節點 +
服務路徑 +
屬性 ID +
屬性名稱 +
價值 +
索引 +
表 ID +
表格名稱
 a| 
網格工作（維護程序）狀態檔案。提供網格作用中、終止、完成、失敗及擱置工作的詳細資料。



 a| 
ILM-STATUS.xml
 a| 
節點 +
服務途徑 +
屬性 ID +
屬性名稱 +
價值 +
索引 +
表 ID +
表格名稱
 a| 
ILM 計量資訊檔案。包含每個節點的 ILM 評估率、以及全網格的計量。



 a| 
ILM 。 xml
 a| 
ILM 原始 XML
 a| 
ILM 作用中原則檔案。包含使用中 ILM 原則的詳細資料、例如儲存池 ID 、擷取行為、篩選器、規則和說明。



 a| 
log.Tgz
 a| 
_n_
 a| 
可下載的記錄檔。包含 `bycast-err.log` 和 `servermanager.log` 從每個節點。



 a| 
Manifest.xml
 a| 
採樣訂單 +
此資料的 AutoSupport 內容檔名 +
此資料項目的說明 +
收集的位元組數 +
收集時間 +
此資料項目的狀態 +
錯誤說明 +
此資料的 AutoSupport 內容類型 +
 a| 
包含 AutoSupport 中繼資料及所有 AutoSupport XML 檔案的簡短說明。



 a| 
NMS-Entitys.xml
 a| 
屬性索引 +
實體 OID +
節點 ID +
裝置型號 ID +
裝置機型版本 +
實體名稱
 a| 
中的群組和服務實體 link:../primer/nodes-and-services.html#storagegrid-services["NMS 樹狀結構"]。提供網格拓撲詳細資料。節點可根據節點上執行的服務來決定。



 a| 
objectS-status.xml
 a| 
節點 +
服務途徑 +
屬性 ID +
屬性名稱 +
價值 +
索引 +
表 ID +
表格名稱
 a| 
物件狀態、包括背景掃描狀態、作用中傳輸、傳輸率、傳輸總數、刪除率、 毀損的片段、遺失的物件、遺失的物件、嘗試的修復、掃描速率、 預估掃描期間、維修完成狀態等。



 a| 
Server-status.xml
 a| 
節點 +
服務途徑 +
屬性 ID +
屬性名稱 +
價值 +
索引 +
表 ID +
表格名稱
 a| 
伺服器組態和事件檔案。包含每個節點的下列詳細資料：平台類型、作業系統、安裝的記憶體、可用記憶體、儲存連線、 儲存應用裝置機箱序號、儲存控制器磁碟機數失敗、運算控制器機箱溫度、運算硬體、運算控制器序號、電源供應器、磁碟機大小、磁碟機類型等。



 a| 
service-status.xml
 a| 
節點 +
服務途徑 +
屬性 ID +
屬性名稱 +
價值 +
索引 +
表 ID +
表格名稱
 a| 
服務節點資訊檔案。包含詳細資料、例如分配的表格空間、可用表格空間、資料庫的 Reaper 指標、區段修復持續時間、修復工作持續時間、自動重新啟動工作、自動終止工作、 還有更多。



 a| 
儲存等級 .xml
 a| 
儲存等級 ID +
儲存等級名稱 +
儲存節點 ID +
儲存節點路徑
 a| 
每個儲存節點的儲存等級定義檔。



 a| 
摘要屬性 .xml
 a| 
群組 OID +
群組路徑 +
摘要屬性 ID +
摘要屬性名稱 +
價值 +
索引 +
表 ID +
表格名稱
 a| 
彙總 StorageGRID 使用資訊的高階系統狀態資料。提供詳細資料、例如網格名稱、網站名稱、每個網格和每個網站的儲存節點數量、授權類型、授權容量和使用量、軟體支援條款、以及 S3 和 Swift 作業的詳細資料。



 a| 
system-arms.xml
 a| 
節點 +
服務途徑 +
嚴重性 +
警用屬性 +
屬性名稱 +
狀態 +
價值 +
觸發時間 +
認可時間
 a| 
系統層級警示（已過時）和狀態資料、用於指出異常活動或潛在問題。



 a| 
system-alerts.xml
 a| 
姓名 +
嚴重性 +
節點名稱 +
警示狀態 +
站台名稱 +
警示觸發時間 +
警示解決時間 +
規則 ID +
節點 ID +
站台 ID +
靜音 +
其他註釋 +
其他標籤
 a| 
指出 StorageGRID 系統中潛在問題的目前系統警示。



 a| 
USERAGENTS.xml
 a| 
使用者代理程式 +
天數 +
HTTP 要求總數 +
擷取的總位元組數 +
擷取的總位元組數 +
提交要求 +
取得要求 +
刪除要求 +
主管要求 +
貼文要求 +
選項要求 +
平均要求時間（毫秒） +
平均投入要求時間（毫秒） +
平均取得要求時間（毫秒） +
平均刪除要求時間（毫秒） +
平均頭部要求時間（毫秒） +
平均要求後時間（毫秒） +
平均選項要求時間（毫秒）
 a| 
以應用程式使用者代理程式為基礎的統計資料。例如、每個使用者代理程式的放置 / 取得 / 刪除 / 顯示頭作業數、以及每項作業的總位元組大小。



 a| 
X-header-data
 a| 
X-NetApp-asup-Generated on +
X-NetApp-asup-hostname+
X-NetApp-asup-OS 版本 +
X-NetApp-asup-Serial-num+
X-NetApp-asup-Subject +
X-NetApp-asup-system-id +
X-NetApp-asup-mode-name +
 a| 
AutoSupport 標頭資料。

|===