---
permalink: s3/head-object.html 
sidebar: sidebar 
keywords: HeadObject 
summary: 您可以使用 S3 HeadObject 要求、從物件擷取中繼資料、而無需傳回物件本身。 
---
= 標題物件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 S3 HeadObject 要求、從物件擷取中繼資料、而無需傳回物件本身。如果物件儲存在雲端儲存池中、您可以使用 HeadObject 來判斷物件的轉換狀態。



== HeadObject 和多個零件物件

您可以使用 `partNumber` 要求參數以擷取多部分或分割物件特定部分的中繼資料。  。 `x-amz-mp-parts-count` 回應元素指出物件有多少部分。

您可以設定 `partNumber` 對於分割 / 多個零件物件和非分割 / 非多個零件物件、則為 1 ；不過、 `x-amz-mp-parts-count` 只會針對分割或多個零件物件傳回回應元素。



== 使用者中繼資料中的UTF-8字元

在使用者定義的中繼資料中、無法剖析或解譯轉義的utf-8字元。StorageGRID使用者定義中繼資料中的轉義式 UTF-8 字元物件的標頭要求不會傳回 `x-amz-missing-meta` 如果金鑰名稱或值包含不可列印的字元、則為標頭。



== 不支援的要求標頭

不支援並傳回下列要求標頭 `XNotImplemented`：

* `x-amz-website-redirect-location`




== 版本管理

如果是 `versionId` 未指定SubResource、此作業會擷取版本控制儲存區中最新版本的物件。如果物件的目前版本是刪除標記、則會傳回「找不到」狀態和 `x-amz-delete-marker` 回應標頭設定為 `true`。



== 使用客戶提供的加密金鑰（SSE-C）要求伺服器端加密標頭

如果物件使用您提供的唯一金鑰加密、請使用這三個標頭。

* `x-amz-server-side-encryption-customer-algorithm`：指定 `AES256`。
* `x-amz-server-side-encryption-customer-key`：指定物件的加密金鑰。
* `x-amz-server-side-encryption-customer-key-MD5`：指定對象加密密鑰的md5摘要。



CAUTION: 您提供的加密金鑰永遠不會儲存。如果您遺失加密金鑰、就會遺失對應的物件。在使用客戶提供的金鑰來保護物件資料之前、請先檢閱中的考量事項 link:using-server-side-encryption.html["使用伺服器端加密"]。



== Cloud Storage Pool 物件的 HeadObject 回應

如果物件儲存在中 link:../ilm/what-cloud-storage-pool-is.html["雲端儲存資源池"]，會傳回下列回應標頭：

* `x-amz-storage-class: GLACIER`
* `x-amz-restore`


回應標頭會提供物件移至雲端儲存集區時的狀態資訊、並選擇性地移轉至無法擷取的狀態、然後還原。

[cols="1a,1a"]
|===
| 物件狀態 | 對 HeadObject 的回應 


 a| 
物件擷取到StorageGRID 不經ILM評估、或儲存在傳統儲存資源池中的物件、或使用銷毀編碼
 a| 
`200 OK` （未傳回特殊回應標頭。）



 a| 
Cloud Storage Pool中的物件、但尚未轉換為無法擷取的狀態
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

「 x-amz-restore ： n未定 要求 = 假」、過期日期 = 「星期六、 7 月 23 日 203000:00 GMT 」

在物件轉換為無法擷取的狀態之前、其值為 `expiry-date` 設定為未來的某段時間。確切的轉換時間不受StorageGRID 此功能的控制。



 a| 
物件已轉換為無法擷取的狀態、但網格上至少也有一個複本
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

「 x-amz-restore ： n未定 要求 = 假」、過期日期 = 「星期六、 7 月 23 日 203000:00 GMT 」

的價值 `expiry-date` 設定為未來的某段時間。

* 注意 * ：如果網格上的複本不可用（例如、儲存節點停機）、您必須發出 link:post-object-restore.html["RestoreObject"] 要求從雲端儲存池還原複本、然後才能成功擷取物件。



 a| 
物件移轉至無法擷取的狀態、而且網格上不存在複本
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`



 a| 
正在從無法擷取的狀態還原的物件
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

「 x-amz-restore ：後續要求 ="true"



 a| 
物件已完全還原至雲端儲存資源池
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

「 x-amz-restore ： n未定 要求 ="false" 、到期日 = 「 2018 年 7 月 23 日星期六 00 ： 00 ： 00 GMT 」

。 `expiry-date` 指出Cloud Storage Pool中的物件何時會傳回無法擷取的狀態。

|===


=== Cloud Storage Pool中的多部份或分段物件

如果您上傳了多個部分的物件、或StorageGRID 是將一個大型物件分割成多個區段、StorageGRID 則透過取樣物件的一部分或區段、決定該物件是否可在Cloud Storage Pool中使用。在某些情況下、當物件的某些部分已經轉換為無法擷取的狀態、或物件的某些部分尚未還原時、 HeadObject 要求可能會錯誤傳回「 x-amz-restore ： non-requstore= 」。



== HeadObject 和跨網格複寫

如果您使用 link:../admin/grid-federation-overview.html["網格同盟"] 和 link:../tenant/grid-federation-manage-cross-grid-replication.html["跨網格複寫"] 為儲存區啟用 S3 用戶端、可發出 HeadObject 要求、以驗證物件的複寫狀態。回應包括 StorageGRID 專屬 `x-ntap-sg-cgr-replication-status` 回應標頭會有下列其中一個值：

[cols="1a,2a"]
|===
| 網格 | 複寫狀態 


 a| 
來源
 a| 
* * 成功 * ：複寫成功。
* * 擱置 * ：物件尚未複寫。
* * 失敗 * ：複寫失敗且持續失敗。使用者必須解決此錯誤。




 a| 
目的地
 a| 
* 複本 * ：物件已從來源網格複寫。

|===

NOTE: 不支援StorageGRID `x-amz-replication-status` 標頭。
