---
permalink: monitor/alarms-reference.html 
sidebar: sidebar 
keywords: alarms, alarms reference 
summary: 下表列出所有舊版預設警報。如果觸發了警示、您可以在此表格中查詢警示代碼、以找出建議的動作。 
---
= 警示參考（舊系統）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下表列出所有舊版預設警報。如果觸發了警示、您可以在此表格中查詢警示代碼、以找出建議的動作。


NOTE: 雖然舊版警示系統仍持續受到支援、但警示系統可提供顯著效益、而且使用起來更輕鬆。

[cols="1a,1a,1a,3a"]
|===
| 程式碼 | 名稱 | 服務 | 建議採取的行動 


 a| 
ABRL
 a| 
可用的屬性中繼
 a| 
BADC、BMS、BARC、BCLB、BCMN、 BLDR、BNMS、BSSM、BDDS
 a| 
儘快恢復與執行屬性轉送服務的服務（ADC服務）的連線。如果沒有連接的屬性轉送、則網格節點無法將屬性值報告給 NMS 服務。因此、NMS服務無法再監控服務狀態、或是更新服務的屬性。

如果問題持續發生、請聯絡技術支援部門。



 a| 
ACMs
 a| 
可用的中繼資料服務
 a| 
BARC、BLDR、BCMN
 a| 
當LDR或ARC服務中斷與DDS服務的連線時、就會觸發警示。如果發生這種情況、則無法處理擷取或擷取交易。如果DDS服務無法使用只是暫時性的問題、則交易可能會延遲。

檢查並還原與DDS服務的連線、以清除此警示、並將服務恢復至完整功能。



 a| 
行動
 a| 
雲端分層服務狀態
 a| 
旋轉
 a| 
僅適用於目標類型為雲端分層的歸檔節點-簡易儲存服務（S3）。

如果歸檔節點的「Acts」（作用）屬性設定為「Read-only Enabled」（唯讀已啟用）或「Read-Write Disabled」（已停用讀寫）、則必須將屬性設定為「Read-Write Enabled」（已啟用讀寫）。

如果因為驗證失敗而觸發重大警示、請確認與目的地儲存區相關的認證資料、並視需要更新值。

如果因任何其他原因而觸發重大警示、請聯絡技術支援部門。



 a| 
ADCA
 a| 
ADC狀態
 a| 
ADC
 a| 
如果觸發了警示、請選取*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* ADC*>*總覽*>*主要*與* ADC*>*警示*>*主要*來判斷警示的原因。

如果問題持續發生、請聯絡技術支援部門。



 a| 
ADCE
 a| 
ADC狀態
 a| 
ADC
 a| 
如果「ADC狀態」的值為「待命」、請繼續監控服務、如果問題持續發生、請聯絡技術支援部門。

如果「ADC狀態」的值為「離線」、請重新啟動服務。如果問題持續發生、請聯絡技術支援部門。



 a| 
AITE
 a| 
擷取狀態
 a| 
BARC
 a| 
僅適用於目標類型為Tivoli Storage Manager（TSM）的歸檔節點。

如果Retrieve State的值正在等待Target、請檢查TSM中介軟體伺服器、並確定其運作正常。如果「歸檔節點」剛新增至StorageGRID 「介紹」系統、請確定歸檔節點與目標外部歸檔儲存系統的連線設定正確。

如果「歸檔擷取狀態」的值為「離線」、請嘗試將狀態更新為「線上」。選取*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* ARC*>*擷取*>*組態*>*主*、選擇*歸檔擷取狀態*>*線上*、然後按一下*套用變更*。

如果問題持續發生、請聯絡技術支援部門。



 a| 
AITU-
 a| 
擷取狀態
 a| 
BARC
 a| 
如果「Retrieve Status（擷取狀態）」值為「Target Error（目標錯誤）」、請檢查目標外部歸檔儲存系統是否有錯誤。

如果「歸檔擷取狀態」的值為「工作階段遺失」、請檢查目標外部歸檔儲存系統、以確保其處於線上狀態並正常運作。檢查與目標的網路連線。

如果「歸檔擷取狀態」的值為「未知錯誤」、請聯絡技術支援部門。



 a| 
Alis
 a| 
傳入屬性工作階段
 a| 
ADC
 a| 
如果屬性轉送上的傳入屬性工作階段數量增加得太多、就表示StorageGRID 該系統已變得不平衡。在正常情況下、屬性工作階段應平均分散於各ADC服務之間。不平衡可能導致效能問題。

如果問題持續發生、請聯絡技術支援部門。



 a| 
alos
 a| 
傳出屬性工作階段
 a| 
ADC
 a| 
ADC服務具有大量的屬性工作階段、而且會變得過載。如果觸發此警報、請聯絡技術支援部門。



 a| 
Alur
 a| 
無法連線的屬性儲存庫
 a| 
ADC
 a| 
檢查NMS服務的網路連線能力、以確保該服務可以聯絡屬性儲存庫。

如果觸發此警報且網路連線正常、請聯絡技術支援部門。



 a| 
AMQS
 a| 
已排入佇列的稽核訊息
 a| 
BADC、BMS、BARC、BCLB、BCMN、 BLDR、BNMS、BDDS
 a| 
如果稽核訊息無法立即轉寄至稽核轉送或儲存庫、則訊息會儲存在磁碟佇列中。如果磁碟佇列已滿、可能會發生中斷。

為了讓您能夠及時回應以避免中斷運作、當磁碟佇列中的訊息數目達到下列臨界值時、便會觸發AMQS警示：

* 注意：超過100、000則訊息
* 次要：至少500、000則訊息
* 主要：至少200、000封郵件
* 關鍵：至少有500、500、500、500、500、500


如果觸發AMQS警示、請檢查系統負載、如果有大量的交易、則警示應會隨著時間自行解決。在這種情況下、您可以忽略警示。

如果警示持續且嚴重性增加、請檢視佇列大小的圖表。如果數在數小時或數天內持續增加、則稽核負載可能超過系統的稽核容量。將稽核層級變更為「錯誤」或「關閉」、以降低用戶端作業率或減少記錄的稽核訊息數。請參閱 link:../monitor/configure-audit-messages.html["設定稽核訊息和記錄目的地"]。



 a| 
AOTE
 a| 
儲存狀態
 a| 
BARC
 a| 
僅適用於目標類型為Tivoli Storage Manager（TSM）的歸檔節點。

如果「儲存狀態」的值正在等待目標、請檢查外部歸檔儲存系統、並確定其運作正常。如果「歸檔節點」剛新增至StorageGRID 「介紹」系統、請確定歸檔節點與目標外部歸檔儲存系統的連線設定正確。

如果Store State的值為「離線」、請檢查「Store Status（儲存狀態）」的值。請先修正任何問題、再將「商店狀態」移回「線上」。



 a| 
AOTU
 a| 
儲存狀態
 a| 
BARC
 a| 
如果「Store Status（儲存狀態）」的值為「Session Lost（工作階段遺失）」、請檢查外部歸檔儲存系統是否已連線並連線。

如果目標錯誤值、請檢查外部歸檔儲存系統是否有錯誤。

如果「Store Status（零售店狀態）」的值為未知錯誤、請聯絡技術支援部門。



 a| 
APMS
 a| 
儲存多重路徑連線
 a| 
超棒
 a| 
如果多重路徑狀態警報顯示為「 Degraded 」（降級）（選擇 * 支援 * > * 工具 * > * 網格拓撲 * 、然後選擇 * 站台 _ * > * 網格節點 _ * > * SSSSS* > * 事件 * ）、請執行下列步驟：

. 插入或更換未顯示任何指示燈的纜線。
. 等待一到五分鐘。
+
插入第一條纜線至少五分鐘後、才拔下另一條纜線。過早拔下可能導致根磁碟區變成唯讀、這需要重新啟動硬體。

. 返回到 *SSSSS* > * 資源 * 頁面、並確認「儲存硬體」區段中的「降級」多重路徑狀態已變更為「標稱」。




 a| 
Arce
 a| 
國家/省/自治區
 a| 
旋轉
 a| 
在所有的ARC元件（複寫、儲存、擷取、目標）都已啟動之前、ARC服務會處於待命狀態。然後移轉至線上。

如果「ARC狀態」的值並未從「待命」轉換為「線上」、請檢查ARC元件的狀態。

如果 ARC 狀態的值為「離線」、請重新啟動服務。如果問題持續發生、請聯絡技術支援部門。



 a| 
AR
 a| 
已佇列的物件
 a| 
旋轉
 a| 
如果卸除式儲存設備因為目標外部歸檔儲存系統發生問題而執行緩慢、或發生多個讀取錯誤、就會觸發此警報。檢查外部歸檔儲存系統是否有錯誤、並確保其運作正常。

在某些情況下、此錯誤可能是因為資料要求率高所致。監控隨著系統活動減少而排入佇列的物件數量。



 a| 
ARRF
 a| 
要求失敗
 a| 
旋轉
 a| 
如果從目標外部歸檔儲存系統擷取失敗、歸檔節點會重試擷取、因為故障可能是暫時性問題所造成。但是、如果物件資料毀損或標記為永遠無法使用、則擷取不會失敗。相反地、歸檔節點會持續重試擷取、而要求失敗的值會持續增加。

此警示可能表示儲存媒體存放所要求的資料已毀損。請檢查外部歸檔儲存系統、以進一步診斷問題。

如果您確定物件資料已不在歸檔中、就必須從StorageGRID 該系統移除物件。如需詳細資訊、請聯絡技術支援部門。

解決觸發此警報的問題後、請重設故障數。選取*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* ARC*>*擷取*>*組態*>*主節點*、選擇*重設要求失敗計數*、然後按一下*套用變更*。



 a| 
ARRV-
 a| 
驗證失敗
 a| 
旋轉
 a| 
若要診斷並修正此問題、請聯絡技術支援部門。

解決觸發此警示的問題之後、請重設失敗次數。選取*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* ARC*>*擷取*>*組態*>*主節點*、選擇*重設驗證失敗計數*、然後按一下*套用變更*。



 a| 
ARVF
 a| 
儲存失敗
 a| 
旋轉
 a| 
此警報可能是目標外部歸檔儲存系統發生錯誤所致。檢查外部歸檔儲存系統是否有錯誤、並確保其運作正常。

解決觸發此警報的問題後、請重設故障數。選取*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* ARC*>*擷取*>*組態*>*主節點*、選擇*重設儲存失敗計數*、然後按一下*套用變更*。



 a| 
ASXP
 a| 
稽核共用
 a| 
AMS
 a| 
如果稽核共用的值為「未知」、就會觸發警示。此警示可能表示管理節點的安裝或組態有問題。

如果問題持續發生、請聯絡技術支援部門。



 a| 
Auma
 a| 
AMS 狀態
 a| 
AMS
 a| 
如果AMS狀態的值為DB Connectivity錯誤、請重新啟動網格節點。

如果問題持續發生、請聯絡技術支援部門。



 a| 
AUME
 a| 
AMS 狀態
 a| 
AMS
 a| 
如果AMS狀態的值為「待命」、請繼續監控StorageGRID 該系統。如果問題持續發生、請聯絡技術支援部門。

如果AMS狀態的值為「離線」、請重新啟動服務。如果問題持續發生、請聯絡技術支援部門。



 a| 
輔助
 a| 
稽核匯出狀態
 a| 
AMS
 a| 
如果觸發警示、請修正基礎問題、然後重新啟動AMS服務。

如果問題持續發生、請聯絡技術支援部門。



 a| 
badd
 a| 
儲存控制器故障磁碟機計數
 a| 
超棒
 a| 
當一個或多個StorageGRID 驅動器出現故障或不是最佳狀態時、就會觸發此警報。視需要更換磁碟機。



 a| 
BASF
 a| 
可用的物件識別碼
 a| 
CMN
 a| 
配置完某個物件時、會為CMN服務分配固定數量的物件識別碼。StorageGRID此警示會在StorageGRID 整個系統耗盡物件識別碼時觸發。

若要分配更多識別碼、請聯絡技術支援部門。



 a| 
重低音
 a| 
識別碼區塊配置狀態
 a| 
CMN
 a| 
根據預設、當無法分配物件識別碼時會觸發警報、因為無法達到 ADC 仲裁。

CMN服務上的識別碼區塊配置需要使用仲裁（50%+ 1）的ADC服務才能連線。如果仲裁不可用、則 CMN 服務將無法分配新的識別碼區塊、直到重新建立 ADC 仲裁為止。如果失去了ADC仲裁數、通常不會立即影響StorageGRID 到這個系統（用戶端仍可擷取和擷取內容）、因為網格中快取了大約一個月的識別資料； 然而StorageGRID 、如果情況持續、則無法擷取新內容。

如果觸發了警示、請調查遺失ADC仲裁的原因（例如、可能是網路或儲存節點故障）、然後採取修正行動。

如果問題持續發生、請聯絡技術支援部門。



 a| 
BRDT
 a| 
運算控制器機箱溫度
 a| 
超棒
 a| 
如果某個應用環境中的運算控制器溫度StorageGRID 超過額定值、就會觸發警示。

檢查硬體元件和環境問題是否過熱。如有必要、請更換元件。



 a| 
BTOF
 a| 
偏移
 a| 
BADC、BLDR、BNMS、BMS、BCLB、 BCMN、BARC
 a| 
如果服務時間（秒）與作業系統時間大不相同、就會觸發警示。在正常情況下、服務應自行重新同步。如果服務時間偏移到離作業系統時間太遠、系統作業可能會受到影響。確認StorageGRID 此系統的時間來源正確無誤。

如果問題持續發生、請聯絡技術支援部門。



 a| 
BTSE
 a| 
時鐘狀態
 a| 
BADC、BLDR、BNMS、BMS、BCLB、 BCMN、BARC
 a| 
如果服務時間與作業系統追蹤的時間不同步、就會觸發警示。在正常情況下、服務應自行重新同步。如果時間偏移距離作業系統時間太遠、系統作業可能會受到影響。確認StorageGRID 此系統的時間來源正確無誤。

如果問題持續發生、請聯絡技術支援部門。



 a| 
CAHP
 a| 
Java堆積使用率百分比
 a| 
DDS
 a| 
如果Java無法以允許系統正常運作的足夠堆空間速率執行垃圾回收、就會觸發警示。警示可能表示使用者工作負載超過DDS中繼資料存放區整個系統可用的資源。在儀表板中查看 ILM 活動、或選取 * 支援 * > * 工具 * > * 網格拓撲 * 、然後選取 * 站台 _ * > * 網格節點 * > * DDS * > * 資源 * > * 總覽 * > * 主要 * 。

如果問題持續發生、請聯絡技術支援部門。



 a| 
卡薩
 a| 
資料儲存區狀態
 a| 
DDS
 a| 
如果Cassandra中繼資料儲存區無法使用、就會發出警示。

檢查Cassandra的狀態：

. 在儲存節點上、以admin和的身分登入 `su` 使用Passwords.txt檔案中所列的密碼進行root。
. 輸入： `service cassandra status`
. 如果Cassandra未執行、請重新啟動： `service cassandra restart`


此警示也可能表示儲存節點的中繼資料存放區（Cassandra資料庫）需要重建。

請參閱中有關疑難排解服務：狀態- Cassandra（SVST）警示的資訊 link:../troubleshoot/troubleshooting-metadata-issues.html["疑難排解中繼資料問題"]。

如果問題持續發生、請聯絡技術支援部門。



 a| 
案例
 a| 
資料儲存區狀態
 a| 
DDS
 a| 
此警示會在安裝或擴充期間觸發、表示新的資料存放區正在加入網格。



 a| 
CCNA
 a| 
運算硬體
 a| 
超棒
 a| 
如果StorageGRID 需要注意運算控制器硬體在某個應用裝置中的狀態、就會觸發此警示。



 a| 
CDLP
 a| 
中繼資料已用空間（百分比）
 a| 
DDS
 a| 
當中繼資料有效空間（CEMS）達到70%滿（次要警示）、90%滿（主要警示）及100%滿（嚴重警示）時、就會觸發此警示。

如果此警報達到 90% 臨界值、 Grid Manager 儀表板上會出現警告。您必須執行擴充程序、才能盡快新增儲存節點。請參閱 link:../expand/index.html["展開網格"]。

如果此警示達到100%臨界值、您必須停止擷取物件、並立即新增儲存節點。Cassandra需要一定的空間來執行必要的作業、例如壓實和修復。如果物件中繼資料使用超過100%的允許空間、這些作業將會受到影響。可能會產生不良的結果。

*附註*：如果您無法新增儲存節點、請聯絡技術支援部門。

新增儲存節點之後、系統會自動在所有儲存節點之間重新平衡物件中繼資料、並清除警示。

另請參閱中有關疑難排解低中繼資料儲存警示的資訊 link:../troubleshoot/troubleshooting-metadata-issues.html["疑難排解中繼資料問題"]。

如果問題持續發生、請聯絡技術支援部門。



 a| 
CMNA
 a| 
CMN 狀態
 a| 
CMN
 a| 
如果CMN狀態的值為「錯誤」、請選取*支援*>*工具*>*網格拓撲*、然後選取*站台_*>*網格節點_*>* CMN*>*總覽*>*主選項*和* CMN*>*警示*>*主選項*、以判斷錯誤原因並疑難排解問題。

當CMNS切換時、在硬體更新主管理節點時、會觸發警示、CMN狀態的值為「No Online CMN」（無線上CMN）（舊CMN狀態的值為「待命」、新的為「線上」）。

如果問題持續發生、請聯絡技術支援部門。



 a| 
CPRC
 a| 
剩餘容量
 a| 
NMS
 a| 
如果剩餘容量（可開啟至NMS資料庫的可用連線數目）低於設定的警示嚴重性、就會觸發警示。

如果觸發警示、請聯絡技術支援部門。



 a| 
CPSA
 a| 
運算控制器電源供應器A
 a| 
超棒
 a| 
如果運算控制器StorageGRID 中的電源供應器A發生問題、就會觸發警示。

如有必要、請更換元件。



 a| 
cPSB
 a| 
運算控制器電源供應器B
 a| 
超棒
 a| 
如果運算控制器StorageGRID 中的電源供應器B有問題、就會觸發警示。

如有必要、請更換元件。



 a| 
CPUT
 a| 
運算控制器CPU溫度
 a| 
超棒
 a| 
如果某個應用程式中的運算控制器CPU溫度StorageGRID 超過額定值、就會觸發警示。

如果儲存節點StorageGRID 是一個物件、StorageGRID 那麼這個功能就是指控制器需要注意。

檢查硬體元件和環境問題是否過熱。如有必要、請更換元件。



 a| 
DNST
 a| 
DNS 狀態
 a| 
超棒
 a| 
安裝完成後、即會在SSM服務中觸發DNST警示。設定DNS之後、新的伺服器資訊會到達所有網格節點、警示就會取消。



 a| 
ECCD
 a| 
偵測到毀損的片段
 a| 
LdR
 a| 
當背景驗證程序偵測到毀損的銷毀編碼片段時、就會觸發警示。如果偵測到毀損的片段、則會嘗試重新建置該片段。將偵測到的毀損片段重設、並將遺失的屬性複製到零、然後加以監控、以查看計數是否再次上升。如果數量增加、儲存節點的基礎儲存設備可能會發生問題。除非遺失或毀損的片段數量違反銷毀程式碼的容錯能力、否則將不會將銷毀編碼物件資料的複本視為遺失；因此、可能會有毀損的片段、而且仍能擷取物件。

如果問題持續發生、請聯絡技術支援部門。



 a| 
ECST
 a| 
驗證狀態
 a| 
LdR
 a| 
此警示指出此儲存節點上銷毀編碼物件資料的背景驗證程序目前狀態。

如果背景驗證程序發生錯誤、就會觸發重大警示。



 a| 
FOPN
 a| 
開啟檔案描述元
 a| 
BADC、BMS、BARC、BCLB、BCMN、 BLDR、BNMS、BSSM、BDDS
 a| 
在尖峰活動期間、FOPN可能變得龐大。如果在活動緩慢期間未減少、請聯絡技術支援部門。



 a| 
HSTE
 a| 
HTTP 狀態
 a| 
BLDR
 a| 
請參閱HSTU的建議行動。



 a| 
HSTU
 a| 
HTTP 狀態
 a| 
BLDR
 a| 
HSTE 和 HSTU 與所有 LDR 流量的 HTTP 相關、包括 S3 、 Swift 和其他內部 StorageGRID 流量。警示表示發生下列其中一種情況：

* HTTP 已手動離線。
* 自動啟動HTTP屬性已停用。
* LDR服務正在關機。


自動啟動HTTP屬性預設為啟用。如果變更此設定、HTTP可能會在重新啟動後維持離線狀態。

如有必要、請等待LDR服務重新啟動。

選取*支援*>*工具*>*網格拓撲*。然後選擇「*儲存節點_*>* LdR*>*組態*」。如果 HTTP 離線、請將其置於線上。確認已啟用「自動啟動HTTP」屬性。

如果 HTTP 保持離線狀態、請聯絡技術支援部門。



 a| 
HTAS
 a| 
自動啟動HTTP
 a| 
LdR
 a| 
指定是否在啟動時自動啟動HTTP服務。這是使用者指定的組態選項。



 a| 
IRSU
 a| 
傳入複寫狀態
 a| 
BLDR、BARC
 a| 
警示表示傳入複寫已停用。確認組態設定：選擇*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* LdR*>*複寫*>*組態*>*主*。



 a| 
lata
 a| 
平均延遲
 a| 
NMS
 a| 
檢查連線問題。

檢查系統活動、確認系統活動增加。系統活動增加將導致屬性資料活動增加。這種增加的活動會導致屬性資料處理延遲。這可能是正常的系統活動、而且會降低。

檢查是否有多個警示。觸發的警示數量過多、可指出平均延遲時間的增加。

如果問題持續發生、請聯絡技術支援部門。



 a| 
LDRE
 a| 
LMR狀態
 a| 
LdR
 a| 
如果LdR狀態的值為「待命」、請繼續監控情況、如果問題持續發生、請聯絡技術支援部門。

如果LdR狀態的值為「離線」、請重新啟動服務。如果問題持續發生、請聯絡技術支援部門。



 a| 
損失
 a| 
遺失物件
 a| 
DDS、LdR
 a| 
當無法從系統的任何位置擷取所要求物件的複本時觸發StorageGRID 。在觸發遺失（遺失物件）警示之前、系統會嘗試從系統的其他位置擷取並取代遺失的物件。

遺失的物件代表資料遺失。當物件的位置數降至零時、若不使用DDS服務、會刻意清除內容以符合ILM原則、「遺失物件」屬性就會遞增。

立即調查遺失（遺失物件）警示。如果問題持續發生、請聯絡技術支援部門。

link:../troubleshoot/troubleshooting-lost-and-missing-object-data.html["疑難排解遺失和遺失的物件資料"]



 a| 
MCEP
 a| 
管理介面憑證過期
 a| 
CMN
 a| 
當用於存取管理介面的憑證即將過期時觸發。

. 從Grid Manager中選擇*組態*>*安全性*>*憑證*。
. 在* Global*索引標籤上、選取*管理介面認證*。
. link:../admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.html#add-a-custom-management-interface-certificate["上傳新的管理介面認證。"]




 a| 
MINQ
 a| 
電子郵件通知已排入佇列
 a| 
NMS
 a| 
檢查裝載NMS服務和外部郵件伺服器的伺服器網路連線。同時確認電子郵件伺服器組態正確無誤。

link:managing-alarms.html["設定警示的電子郵件伺服器設定（舊系統）"]



 a| 
分
 a| 
電子郵件通知狀態
 a| 
BNMS
 a| 
如果NMS服務無法連線至郵件伺服器、則會觸發次要警示。檢查裝載NMS服務和外部郵件伺服器的伺服器網路連線。同時確認電子郵件伺服器組態正確無誤。

link:managing-alarms.html["設定警示的電子郵件伺服器設定（舊系統）"]



 a| 
錯過
 a| 
NMS介面引擎狀態
 a| 
BNMS
 a| 
如果管理節點上收集和產生介面內容的NMS介面引擎與系統中斷連線、就會觸發警示。請檢查伺服器管理員、判斷伺服器個別應用程式是否已關閉。



 a| 
南
 a| 
網路自動交涉設定
 a| 
超棒
 a| 
檢查網路介面卡組態。此設定必須符合網路路由器和交換器的喜好設定。

不正確的設定可能會嚴重影響系統效能。



 a| 
NDUP
 a| 
網路雙工設定
 a| 
超棒
 a| 
檢查網路介面卡組態。此設定必須符合網路路由器和交換器的喜好設定。

不正確的設定可能會嚴重影響系統效能。



 a| 
NLNK
 a| 
網路連結偵測
 a| 
超棒
 a| 
檢查連接埠和交換器的網路纜線連線。

檢查網路路由器、交換器和介面卡組態。

重新啟動伺服器。

如果問題持續發生、請聯絡技術支援部門。



 a| 
NERR
 a| 
接收錯誤
 a| 
超棒
 a| 
NERRER警示的原因如下：

* 轉送錯誤修正（FEC）不符
* 交換器連接埠和NIC MTU不符
* 高連結錯誤率
* NIC環狀緩衝區溢位


請參閱中的網路接收錯誤（NERR）警示疑難排解資訊 link:../troubleshoot/troubleshooting-network-hardware-and-platform-issues.html["疑難排解網路、硬體及平台問題"]。



 a| 
NRLY
 a| 
可用的稽核中繼
 a| 
BADC、BARC、BCLB、BCMN、BLDR、 BNMS、BDDS
 a| 
如果稽核中繼未連線至 ADC 服務、則無法回報稽核事件。在連線恢復之前、使用者將無法使用這些連線。

盡快恢復與某個ADC服務的連線。

如果問題持續發生、請聯絡技術支援部門。



 a| 
NSC
 a| 
NMS 狀態
 a| 
NMS
 a| 
如果NMS狀態的值為「DB Connectivity錯誤」、請重新啟動服務。如果問題持續發生、請聯絡技術支援部門。



 a| 
NSCE
 a| 
NMS State
 a| 
NMS
 a| 
如果NMS狀態的值為「待命」、請繼續監控、如果問題持續發生、請聯絡技術支援部門。

如果 NMS State 的值為「離線」、請重新啟動服務。如果問題持續發生、請聯絡技術支援部門。



 a| 
NSPD
 a| 
速度
 a| 
超棒
 a| 
這可能是網路連線或驅動程式相容性問題所造成。如果問題持續發生、請聯絡技術支援部門。



 a| 
NTBR
 a| 
可用的表空間
 a| 
NMS
 a| 
如果觸發了警示、請檢查資料庫使用率的變更速度。突然下降（而非隨時間逐漸改變）代表錯誤狀況。如果問題持續發生、請聯絡技術支援部門。

調整警示臨界值可讓您在需要分配額外儲存設備時主動管理。

如果可用空間達到低臨界值（請參閱警示臨界值）、請聯絡技術支援部門以變更資料庫配置。



 a| 
nter
 a| 
傳輸錯誤
 a| 
超棒
 a| 
無需手動重設、即可清除這些錯誤。如果沒有清除、請檢查網路硬體。檢查介面卡硬體和驅動程式是否已正確安裝並設定為可搭配網路路由器和交換器使用。

解決基礎問題後、請重設計數器。選取*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* SES*>*資源*>*組態*>*主節點*、選擇*重設傳輸錯誤計數*、然後按一下*套用變更*。



 a| 
NTFQ
 a| 
NTP頻率偏移
 a| 
超棒
 a| 
如果頻率偏移超過設定的臨界值、則可能是本機時鐘發生硬體問題。如果問題持續發生、請聯絡技術支援部門以安排更換事宜。



 a| 
NTLK
 a| 
NTP鎖定
 a| 
超棒
 a| 
如果NTP精靈未鎖定外部時間來源、請檢查與指定外部時間來源的網路連線能力、可用度及穩定性。



 a| 
NTOF
 a| 
NTP時間偏移
 a| 
超棒
 a| 
如果時間偏移超過設定的臨界值、則可能是本機時鐘的振盪器發生硬體問題。如果問題持續發生、請聯絡技術支援部門以安排更換事宜。



 a| 
NTSJ
 a| 
選定的時間來源提交人
 a| 
超棒
 a| 
此值表示NTP在本機伺服器上作為參考的時間來源的可靠性和穩定性。

如果觸發了警示、可能表示時間來源的振盪器故障、或是與時間來源的WAN連結發生問題。



 a| 
Ntsu
 a| 
NTP 狀態
 a| 
超棒
 a| 
如果NTP狀態的值未執行、請聯絡技術支援部門。



 a| 
OPST
 a| 
整體電力狀態
 a| 
超棒
 a| 
如果某個應用程式的電力StorageGRID 偏離建議的操作電壓、就會觸發警示。

檢查電源供應器A或B的狀態、以判斷哪些電源供應器運作異常。

如有必要、請更換電源供應器。



 a| 
OQRT
 a| 
已隔離的物件
 a| 
LdR
 a| 
當物件由StorageGRID 還原系統自動還原之後、隔離的物件就能從隔離目錄中移除。

. 選取*支援*>*工具*>*網格拓撲*。
. 選擇*站台*>*儲存節點*>* LdR*>*驗證*>*組態*>*主要*。
. 選取*刪除隔離的物件*。
. 按一下*套用變更*。


隔離的物件會移除、並將計數重設為零。



 a| 
ORSU
 a| 
傳出複寫狀態
 a| 
BLDR、BARC
 a| 
警示表示無法進行輸出複寫：儲存設備處於無法擷取物件的狀態。如果手動停用傳出複寫、就會觸發警示。選取*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* LdR*>*複寫*>*組態*。

如果LMR服務無法進行複寫、就會觸發警示。選取*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* LdR*>*儲存設備*。



 a| 
OSLF
 a| 
機櫃狀態
 a| 
超棒
 a| 
如果儲存設備儲存櫃中某個元件的狀態降級、就會觸發警示。儲存櫃元件包括IOM、風扇、電源供應器和磁碟機抽屜。如果觸發此警報、請參閱設備的維護說明。



 a| 
PMEM
 a| 
服務記憶體使用率（百分比）
 a| 
BADC、BMS、BARC、BCLB、BCMN、 BLDR、BNMS、BSSM、BDDS
 a| 
可以有超過Y% RAM的值、其中Y代表伺服器使用的記憶體百分比。

80%以下的數字是正常的。超過90%被視為問題。

如果單一服務的記憶體使用率偏高、請監控情況並調查。

如果問題持續發生、請聯絡技術支援部門。



 a| 
SSA
 a| 
電源供應器A狀態
 a| 
超棒
 a| 
如果供應器A StorageGRID 的電源供應器偏離建議的操作電壓、就會觸發警示。

如有必要、請更換電源供應器A



 a| 
PSBs
 a| 
電源供應器B狀態
 a| 
超棒
 a| 
如果供應器B StorageGRID 的電源供應器偏離建議的操作電壓、就會觸發警示。

如有必要、請更換電源供應器B



 a| 
RDTE
 a| 
Tivoli Storage Manager狀態
 a| 
BARC
 a| 
僅適用於目標類型為Tivoli Storage Manager（TSM）的歸檔節點。

如果Tivoli Storage Manager狀態的值為「離線」、請檢查Tivoli Storage Manager狀態並解決任何問題。

將元件重新連線。選取*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* ARC*>*目標*>*組態*>*主要*、選擇* Tivoli Storage Manager狀態*>*線上*、然後按一下*套用變更*。



 a| 
RDTU
 a| 
Tivoli Storage Manager狀態
 a| 
BARC
 a| 
僅適用於目標類型為Tivoli Storage Manager（TSM）的歸檔節點。

如果Tivoli Storage Manager狀態的值為組態錯誤、且歸檔節點剛剛新增至StorageGRID 整個作業系統、請確定TSM中介軟體伺服器已正確設定。

如果Tivoli Storage Manager狀態的值為「連線失敗」或「連線失敗、重新執行」、請檢查TSM中介軟體伺服器上的網路組態、以及TSM中介軟體伺服器與StorageGRID 作業系統之間的網路連線。

如果 Tivoli Storage Manager 狀態的值為驗證失敗或驗證失敗、請重新連線、 StorageGRID 系統可以連線至 TSM 中介軟體伺服器、但無法驗證連線。檢查TSM中介軟體伺服器是否設定正確的使用者、密碼和權限、然後重新啟動服務。

如果Tivoli Storage Manager狀態的值為「工作階段失敗」、表示已建立的工作階段已意外遺失。檢查TSM中介軟體伺服器與StorageGRID 該系統之間的網路連線。檢查中介軟體伺服器是否有錯誤。

如果Tivoli Storage Manager狀態的值為未知錯誤、請聯絡技術支援部門。



 a| 
RIRF
 a| 
傳入複製-失敗
 a| 
BLDR、BARC
 a| 
傳入複製：在高負載或暫時網路中斷期間、可能會發生「失敗」警示。系統活動減少後、此警示應會清除。如果複製失敗次數持續增加、請尋找網路問題、並確認來源和目的地的LDR和ARC服務已上線且可供使用。

若要重設計數、請選取*支援*>*工具*>*網格拓撲*、然後選取*站台_*>*網格節點_*>* LdR*>*複寫*>*組態*>*主要*。選取*重設傳入複寫失敗計數*、然後按一下*套用變更*。



 a| 
RIR
 a| 
傳入複製：佇列中
 a| 
BLDR、BARC
 a| 
在高負載或暫時網路中斷期間、可能會發生警示。系統活動減少後、此警示應會清除。如果佇列複製的計數持續增加、請尋找網路問題、並確認來源和目的地的LDR和ARC服務已上線且可供使用。



 a| 
RORQ
 a| 
傳出複製—已排入佇列
 a| 
BLDR、BARC
 a| 
傳出複寫佇列包含要複製的物件資料、以滿足用戶端要求的ILM規則和物件。

系統過載可能會造成警示。等待系統活動減少時、查看警示是否清除。如果警示再次發生、請新增儲存節點來新增容量。



 a| 
SAVP
 a| 
可用空間總計（百分比）
 a| 
LdR
 a| 
如果可用空間達到低臨界值、選項包括擴充StorageGRID 支援中心系統、或是透過歸檔節點將物件資料移至歸檔。



 a| 
管制協議
 a| 
狀態
 a| 
CMN
 a| 
如果作用中網格工作的「狀態」值為「錯誤」、請查詢網格工作訊息。選取*支援*>*工具*>*網格拓撲*。然後選擇「*站台_*>*網格節點_*>* CMN*>*網格工作*>*總覽*>*主要*」。網格工作訊息會顯示有關錯誤的資訊（例如、「檢查節點 12130011 上的失敗」）。

調查並修正問題之後、請重新啟動網格工作。選取*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* CMN*>*網格工作*>*組態*>*主*、然後選取*動作*>*執行*。

如果要停止之網格工作的狀態值為「錯誤」、請重試結束網格工作。

如果問題持續發生、請聯絡技術支援部門。



 a| 
SCEP
 a| 
儲存API服務端點憑證過期
 a| 
CMN
 a| 
當用於存取儲存API端點的憑證即將過期時觸發。

. 選擇*組態*>*安全性*>*憑證*。
. 在* Global*索引標籤上、選取* S3和Swift API認證*。
. link:../admin/configuring-custom-server-certificate-for-storage-node.html#add-a-custom-s3-and-swift-api-certificate["上傳新的S3和Swift API認證。"]




 a| 
SCHR
 a| 
狀態
 a| 
CMN
 a| 
如果歷史網格工作的狀態值為「已中止」、請調查原因、並視需要再次執行工作。

如果問題持續發生、請聯絡技術支援部門。



 a| 
SCSA
 a| 
儲存控制器A
 a| 
超棒
 a| 
如果在產品中的儲存控制器A發生問題、就會觸發警示StorageGRID 。

如有必要、請更換元件。



 a| 
SCSB
 a| 
儲存控制器B
 a| 
超棒
 a| 
如果產品的儲存控制器B發生問題、就會觸發警示StorageGRID 。

如有必要、請更換元件。

部分應用裝置機型沒有儲存控制器 B



 a| 
SHLH
 a| 
健全狀況
 a| 
LdR
 a| 
如果物件存放區的健全狀況值為錯誤、請檢查並修正：

* 掛載的Volume有問題
* 檔案系統錯誤




 a| 
SLSA
 a| 
CPU負載平均
 a| 
超棒
 a| 
系統的價值越高。

如果CPU負載平均值持續偏高、則應調查系統中的交易數量、以判斷這是否是因為當時負載過重所致。查看CPU負載平均圖表：選擇*支援*>*工具*>*網格拓撲*。然後選擇*站台_*>*網格節點_*>* SUS*>*資源*>*報告*>*圖表*。

如果系統負載不沉重、而且問題仍然存在、請聯絡技術支援部門。



 a| 
SMST
 a| 
記錄監控狀態
 a| 
超棒
 a| 
如果記錄監控狀態的值持續未連線一段時間、請聯絡技術支援部門。



 a| 
SMtT
 a| 
活動總計
 a| 
超棒
 a| 
如果「事件總數」的值大於零、請檢查是否有已知事件（例如網路故障）可能是原因。除非已清除這些錯誤（也就是計數已重設為0）、否則會觸發事件總數警示。

解決問題時、請重設計數器以清除警示。選擇*節點*>*站台*>*網格節點_*>*事件*>*重設事件計數*。


NOTE: 若要重設事件計數、您必須擁有 Grid 拓撲頁面組態權限。

如果「事件總數」的值為零、或數字增加、但問題持續存在、請聯絡技術支援部門。



 a| 
SNST
 a| 
狀態
 a| 
CMN
 a| 
警示表示儲存網格工作組合時發生問題。如果「Status（狀態）」的值為「Checkpoint Error（檢查點錯誤）」或「Quorum not ached（未達到仲裁）」、請確認大部分的ADC服務都已連接StorageGRID 到該系統（50%加一）、然後等待幾分鐘。

如果問題持續發生、請聯絡技術支援部門。



 a| 
Soss
 a| 
儲存作業系統狀態
 a| 
超棒
 a| 
如果 SANtricity 作業系統指出 StorageGRID 應用裝置中的元件發生「需要注意」問題、就會觸發警報。

選擇*節點*。然後選擇*設備儲存節點*>*硬體*。向下捲動以檢視每個元件的狀態。在 SANtricity OS 中、檢查其他應用裝置元件以找出問題所在。



 a| 
SSMA
 a| 
超音波狀態
 a| 
超棒
 a| 
如果「超音波狀態」的值為「錯誤」、請選取「*支援*>*工具*>*網格拓撲*」、然後選取「*站台_*>*網格節點_*>*「超音波」>「*總覽*」>「*警示*」、以判斷警示的原因。

如果問題持續發生、請聯絡技術支援部門。



 a| 
Ssme
 a| 
超音波狀態
 a| 
超棒
 a| 
如果「SSM狀態」的值為「待命」、請繼續監控、如果問題持續發生、請聯絡技術支援部門。

如果「超線狀態」的值為「離線」、請重新啟動服務。如果問題持續發生、請聯絡技術支援部門。



 a| 
SSTS
 a| 
儲存狀態
 a| 
BLDR
 a| 
如果「儲存狀態」的值為「可用空間不足」、則儲存節點上沒有可用的儲存空間、資料擷取則會重新導向至其他可用的儲存節點。您可以繼續從此網格節點傳送擷取要求。

應增加額外的儲存空間。它不會影響終端使用者功能、但在新增額外儲存設備之前、警示仍會持續發生。

如果「儲存狀態」的值為「Volume（s）不可用」、則儲存設備的一部分將無法使用。無法從這些磁碟區進行儲存與擷取。請查看磁碟區的健全狀況以取得更多資訊：選取*支援*>*工具*>*網格拓撲*。然後選擇「*站台_*>*網格節點_*>* LdR*>*儲存設備*>*總覽*>*主要*」。Volume的健全狀況列在「物件存放區」下。

如果「儲存狀態」的值為「錯誤」、請聯絡技術支援部門。

link:../troubleshoot/troubleshooting-storage-status-alarm.html["疑難排解儲存狀態（SSTS）警示"]



 a| 
SVST
 a| 
狀態
 a| 
超棒
 a| 
當與非執行中服務相關的其他警示解決時、就會清除此警示。追蹤來源服務警示以恢復作業。

選取*支援*>*工具*>*網格拓撲*。然後選擇「*站台_*>*網格節點_*>* SES*>*服務*>*總覽*>*主要*」。當服務狀態顯示為「未執行」時、其狀態會以管理方式關閉。服務的狀態可能因為下列原因而列為「未執行」：

* 服務已手動停止 (`/etc/init.d/<service\> stop`）。
* MySQL資料庫發生問題、伺服器管理程式會關閉MI服務。
* 已新增網格節點、但尚未啟動。
* 在安裝期間、網格節點尚未連線至管理節點。


如果某項服務被列為未執行中、請重新啟動該服務 (`/etc/init.d/<service\> restart`）。

此警示也可能表示儲存節點的中繼資料存放區（Cassandra資料庫）需要重建。

如果問題持續發生、請聯絡技術支援部門。

link:../troubleshoot/troubleshooting-metadata-issues.html["疑難排解服務：狀態- Cassandra（SVST）警示"]



 a| 
TMEM
 a| 
安裝的記憶體
 a| 
超棒
 a| 
如果節點執行的安裝記憶體少於24 GiB、可能會導致效能問題和系統不穩定。系統上安裝的記憶體容量應至少增加至24 GiB。



 a| 
TPOP
 a| 
擱置作業
 a| 
ADC
 a| 
訊息佇列可能表示ADC服務過載。無法將太少的ADC服務連線StorageGRID 至該系統。在大型部署中、ADC服務可能需要新增運算資源、或者系統可能需要額外的ADC服務。



 a| 
密執安
 a| 
可用記憶體
 a| 
超棒
 a| 
如果可用RAM不足、請判斷這是硬體或軟體問題。如果不是硬體問題、或可用記憶體低於50 MB（預設警示臨界值）、請聯絡技術支援。



 a| 
做為
 a| 
可用的項目
 a| 
超棒
 a| 
這表示需要額外的儲存空間。聯絡技術支援。



 a| 
VMfR
 a| 
可用空間
 a| 
超棒
 a| 
如果可用空間的值太低（請參閱警示臨界值）、則需要調查是否有記錄檔超出比例、或物件佔用太多磁碟空間（請參閱警示臨界值）、而這些資料需要減少或刪除。

如果問題持續發生、請聯絡技術支援部門。



 a| 
VMST
 a| 
狀態
 a| 
超棒
 a| 
如果掛載Volume的Status值為Unknown（未知）、就會觸發警示。如果值為「未知」或「離線」、則表示由於基礎儲存設備發生問題、因此無法掛載或存取磁碟區。



 a| 
VPRI
 a| 
驗證優先順序
 a| 
BLDR、BARC
 a| 
依預設、驗證優先順序的值為Adaptive（調適性）。如果「驗證優先順序」設定為「高」、則會觸發警示、因為儲存驗證可能會減慢服務的正常運作速度。



 a| 
VSTU
 a| 
物件驗證狀態
 a| 
BLDR
 a| 
選取*支援*>*工具*>*網格拓撲*。然後選擇「*站台_*>*網格節點_*>* LdR*>*儲存設備*>*總覽*>*主要*」。

檢查作業系統是否有任何區塊裝置或檔案系統錯誤的跡象。

如果「物件驗證狀態」的值為「未知錯誤」、通常表示低層級的檔案系統或硬體問題（I/O錯誤）、會使「儲存驗證」工作無法存取儲存的內容。聯絡技術支援。



 a| 
XAMS
 a| 
無法連線的稽核儲存庫
 a| 
BADC、BARC、BCLB、BCMN、BLDR、 BNMS
 a| 
檢查與管理節點所在伺服器的網路連線。

如果問題持續發生、請聯絡技術支援部門。

|===