---
permalink: maintain/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, installation files, download 
summary: 您必須先下載軟體並解壓縮檔案、才能恢復 StorageGRID 節點。 
---
= 下載並解壓縮StorageGRID 安裝檔案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須先下載軟體並解壓縮檔案、才能恢復 StorageGRID 節點。

您必須使用StorageGRID 目前在網格上執行的版本。

.步驟
. 判斷目前安裝的軟體版本。從Grid Manager頂端、選取說明圖示、然後選取*關於*。
. 請前往NetApp下載頁StorageGRID 面以瞭解決此問題。
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下載StorageGRID"^]

. 選取StorageGRID 目前在網格上執行的版本的功能。
+
下列格式的軟件版本：11.x.y。StorageGRID

. 以您NetApp帳戶的使用者名稱和密碼登入。
. 閱讀終端使用者授權合約、選取核取方塊、然後選取 * 接受並繼續 * 。
. 在下載頁面的「*安裝StorageGRID S編*」欄中、選取 `.tgz` 或 `.zip` 適用於您的平台的檔案。
+
安裝歸檔檔檔案中顯示的版本必須符合目前安裝的軟體版本。

+
使用 `.zip` 檔案（如果您執行的是Windows）。

+
[cols="1a,2a"]
|===
| 平台 | 安裝歸檔 


 a| 
Red Hat Enterprise Linux
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu或DEBIANOR應用裝置
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 
|===
. 下載並解壓縮歸檔檔案。
. 根據您的平台和需要恢復的網格節點、依照您平台的適當步驟來選擇所需的檔案。
+
每個平台步驟中所列的路徑、都是相對於歸檔檔案所安裝的頂層目錄。

. 如果您要還原 link:../rhel/index.html["Red Hat Enterprise Linux 系統"]下、選取適當的檔案。


[cols="1a,1a"]
|===
| 路徑和檔案名稱 | 說明 


| ./rpms/README  a| 
說明StorageGRID 包含在更新檔中的所有檔案的文字檔。



| ./rpms/NLF000000.txt  a| 
不提供產品任何支援權利的免費授權。



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
用於在 RHEL 主機上安裝 StorageGRID 節點映像的 RPM 套件。



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
用於在 RHEL 主機上安裝 StorageGRID 主機服務的 RPM 套件。



| 部署指令碼工具 | 說明 


| ./rpms/configure-storagegrid.py  a| 
Python指令碼、用於自動化StorageGRID 組態的功能。



| ./rpms/configure-sga.py  a| 
Python指令碼、用於自動化StorageGRID 設定不必要的應用程式。



| ./rpms/configure儲存格RID、same.json  a| 
搭配使用的範例組態檔案 `configure-storagegrid.py` 指令碼：



| ./rpms/storagegrid-ssoauth.py  a| 
啟用單一登入時、您可用來登入Grid Management API的Python指令碼範例。您也可以將此指令碼用於 Ping 聯合。



| ./rpms/configure儲存格RID、blank、json  a| 
與搭配使用的空白組態檔 `configure-storagegrid.py` 指令碼：



| ./rpms/Extas/Ansible  a| 
範例 Ansible 角色和教戰手冊、用於設定 StorageGRID 容器部署的 RHEL 主機。您可以視需要自訂角色或方針。



| ./rpms/storagegrid-ssoauth-azure.py  a| 
使用 Active Directory 或 Ping 聯合啟用單一登入（ SSO ）時、可以用來登入 Grid Management API 的 Python 指令碼範例。



| ./rpms/sstoragegrit-soauth-azure.js  a| 
由該夥伴所呼叫的輔助程式指令碼 `storagegrid-ssoauth-azure.py` Python 指令碼可與 Azure 執行 SSO 互動。



| ./rpms/Extps/API-架構  a| 
API架構StorageGRID 。

* 注意 * ：在執行升級之前、如果您沒有非正式作業的 StorageGRID 環境來進行升級相容性測試、您可以使用這些架構來確認您為使用 StorageGRID 管理 API 所撰寫的任何程式碼、都與新的 StorageGRID 版本相容。

|===
. 如果您要還原 link:../ubuntu/index.html["Ubuntu或Debian系統"]下、選取適當的檔案。


[cols="1a,1a"]
|===
| 路徑和檔案名稱 | 說明 


| 每個問題/讀我檔案  a| 
說明StorageGRID 包含在更新檔中的所有檔案的文字檔。



| ./cebs/NLF000000.txt  a| 
非正式作業的NetApp授權檔案、可用於測試及概念驗證部署。



| ./cebs/storagegrid-webscale-images-version-SHA.deb  a| 
Deb套件、用於在StorageGRID Ubuntu或Debian主機上安裝不含節點的映像。



| ./cebs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
檔案的md5 Checksum `/debs/storagegrid-webscale-images-version-SHA.deb`。



| ./cebs/storagegrid-webscale-service-version-SHA.deb  a| 
Deb套件、用於在StorageGRID Ubuntu或Debian主機上安裝支援功能主機服務。



| 部署指令碼工具 | 說明 


| ./cebs/configure-storagegrid.py  a| 
Python指令碼、用於自動化StorageGRID 組態的功能。



| ./cebs/configure-sga.py  a| 
Python指令碼、用於自動化StorageGRID 設定不必要的應用程式。



| ./cebs/storagegrid-ssoauth.py  a| 
啟用單一登入時、您可用來登入Grid Management API的Python指令碼範例。您也可以將此指令碼用於 Ping 聯合。



| ./cebs/configure儲存格RID、same.json  a| 
搭配使用的範例組態檔案 `configure-storagegrid.py` 指令碼：



| ./cebs/configure儲存格GRID、blank、json  a| 
與搭配使用的空白組態檔 `configure-storagegrid.py` 指令碼：



| /扣款/額外費用/可選  a| 
範例Ansible角色與方針、可用來設定Ubuntu或Debian主機以StorageGRID 進行列舉容器部署。您可以視需要自訂角色或方針。



| ./debs/storagegrid-ssoauth-azure.py  a| 
使用 Active Directory 或 Ping 聯合啟用單一登入（ SSO ）時、可以用來登入 Grid Management API 的 Python 指令碼範例。



| /debs/storagegRID -soaut-azure.js  a| 
由該夥伴所呼叫的輔助程式指令碼 `storagegrid-ssoauth-azure.py` Python 指令碼可與 Azure 執行 SSO 互動。



| ./扣款/其他項目/ API架構  a| 
API架構StorageGRID 。

* 注意 * ：在執行升級之前、如果您沒有非正式作業的 StorageGRID 環境來進行升級相容性測試、您可以使用這些架構來確認您為使用 StorageGRID 管理 API 所撰寫的任何程式碼、都與新的 StorageGRID 版本相容。

|===
. 如果您要還原 link:../vmware/index.html["VMware系統"]下、選取適當的檔案。


[cols="1a,1a"]
|===
| 路徑和檔案名稱 | 說明 


| /vSphere/README  a| 
說明StorageGRID 包含在更新檔中的所有檔案的文字檔。



| ./vSphere/NLF000000.txt  a| 
不提供產品任何支援權利的免費授權。



| /vSphere/NetApp-SG-version -SHA-vmdk  a| 
用來做為建立網格節點虛擬機器範本的虛擬機器磁碟檔案。



| ./vSphere/vsphere-primer-admin.OVF

./vSphere/vsphere-primer-admin.mf  a| 
開放式虛擬化格式範本檔案 (`.ovf`）和資訊清單檔案 (`.mf`）以部署主管理節點。



| ./vSphere/vSphere-non-primer-admin.OVF

./vSphere/vsphere-non-primary 管理 .mf  a| 
範本檔案 (`.ovf`）和資訊清單檔案 (`.mf`）以部署非主要管理節點。



| ./vSphere/vsphere-archive 。 OVF

./vSphere/vsphere-archive  a| 
範本檔案 (`.ovf`）和資訊清單檔案 (`.mf`）以部署歸檔節點。



| ./vSphere/vsphere-gateway.OVF

./vSphere/vsphere-gateway.mf  a| 
範本檔案 (`.ovf`）和資訊清單檔案 (`.mf`）以部署閘道節點。



| ./vSphere/vsphere-storage 。 OVF

./vSphere/vsphere-storage .mf  a| 
範本檔案 (`.ovf`）和資訊清單檔案 (`.mf`）以部署虛擬機器型儲存節點。



| 部署指令碼工具 | 說明 


| ./vSphere/deploy-vsphere-ovftool.sh  a| 
Bash Shell指令碼、用於自動化虛擬網格節點的部署。



| ./vSphere/deploy-vsphere-ovftool-sample.ini  a| 
搭配使用的範例組態檔案 `deploy-vsphere-ovftool.sh` 指令碼：



| ./vSphere/configure-storagegrid.py  a| 
Python指令碼、用於自動化StorageGRID 組態的功能。



| ./vSphere/configure-sga.py  a| 
Python指令碼、用於自動化StorageGRID 設定不必要的應用程式。



| ./vSphere/storagegrid-ssoauth.py  a| 
啟用單一登入（ SSO ）時、您可以使用 Python 指令碼範例登入 Grid Management API 。您也可以將此指令碼用於 Ping 聯合。



| /vSphere/configure-storagegrid、same.json  a| 
搭配使用的範例組態檔案 `configure-storagegrid.py` 指令碼：



| /vSphere/configure-storagegrid、blank.json  a| 
與搭配使用的空白組態檔 `configure-storagegrid.py` 指令碼：



| ./vSphere/storagegrid-ssoauth-azure.py  a| 
使用 Active Directory 或 Ping 聯合啟用單一登入（ SSO ）時、可以用來登入 Grid Management API 的 Python 指令碼範例。



| ./svSphere/storagegRID -soauth-azure.js  a| 
由該夥伴所呼叫的輔助程式指令碼 `storagegrid-ssoauth-azure.py` Python 指令碼可與 Azure 執行 SSO 互動。



| /vSphere/Extras / API架構  a| 
API架構StorageGRID 。

* 注意 * ：在執行升級之前、如果您沒有非正式作業的 StorageGRID 環境來進行升級相容性測試、您可以使用這些架構來確認您為使用 StorageGRID 管理 API 所撰寫的任何程式碼、都與新的 StorageGRID 版本相容。

|===
. 如果您要還原StorageGRID 以應用程式為基礎的系統、請選取適當的檔案。


[cols="1a,1a"]
|===
| 路徑和檔案名稱 | 說明 


| ./cebs/storagegrid-webscale-images-version-SHA.deb  a| 
DEB套件可在StorageGRID 您的應用裝置上安裝不含節點的影像。



| ./cebs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
檔案的md5 Checksum `/debs/storagegridwebscale-
images-version-SHA.deb`。

|===

NOTE: 在設備安裝方面、只有在您需要避免網路流量時才需要這些檔案。應用裝置可從主要管理節點下載所需的檔案。
