---
permalink: maintain/powering-down-host.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: 在關閉主機電源之前、您必須停止該主機上所有網格節點上的服務。 
---
= 關閉主機電源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在關閉主機電源之前、您必須停止該主機上所有網格節點上的服務。

.步驟
. 登入網格節點：
+
.. 輸入下列命令： `ssh admin@_grid_node_IP_`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：
.. 輸入下列命令以切換至root： `su -`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：


+
當您以root登入時、提示會從變更 `$` 至 `#`。

. 停止節點上執行的所有服務： `service servermanager stop`
+
服務關機最多需要15分鐘、您可能想要從遠端登入系統、以監控關機程序。

. 針對主機上的每個節點重複步驟1和2。
. 如果您有Linux主機：
+
.. 登入主機作業系統。
.. 停止節點： `storagegrid node stop`
.. 關閉主機作業系統。


. 如果節點是在VMware虛擬機器上執行、或是在應用裝置節點上執行、請發出關機命令： `shutdown -h now`
+
執行此步驟時、無論結果為何 `service servermanager stop` 命令。

+

NOTE: 在您發行之後 `shutdown -h now` 在應用裝置節點上執行命令時、您必須重新啟動應用裝置電源、才能重新啟動節點。

+
對於應用裝置、此命令會關閉控制器、但應用裝置仍會開啟電源。您必須完成下一步。

. 如果您要關閉應用裝置節點的電源、請遵循應用裝置的步驟。
+
[role="tabbed-block"]
====
.SGF6112
--
.. 關閉產品電源。
.. 等待藍色電源LED燈關閉。


--
.SG6000
--
.. 等待儲存控制器背面的綠色快取作用中LED關閉。
+
當需要將快取的資料寫入磁碟機時、此LED會亮起。您必須等待此LED燈關閉、才能關閉電源。

.. 關閉產品電源、然後等待藍色電源LED燈關閉。


--
.SG5700
--
.. 等待儲存控制器背面的綠色快取作用中LED關閉。
+
當需要將快取的資料寫入磁碟機時、此LED會亮起。您必須等待此LED燈關閉、才能關閉電源。

.. 關閉產品電源、並等待所有LED和七段顯示活動停止。


--
.SG110 或 SG1100
--
.. 關閉產品電源。
.. 等待藍色電源LED燈關閉。


--
.SG100 或 SG1000
--
.. 關閉產品電源。
.. 等待藍色電源LED燈關閉。


--
====
. 登出命令Shell： `exit`


.相關資訊
https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112 儲存設備"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["SG6000儲存設備"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["SG5700 儲存設備"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["SG110 和 SG1100 服務應用裝置"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100與SG1000服務應用裝置"^]
