---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: 您可以從節點的命令Shell關閉網格節點。 
---
= 關閉網格節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從節點的命令Shell關閉網格節點。

.開始之前
* 您擁有 `Passwords.txt` 檔案：


.關於這項工作
執行此程序之前、請先檢閱下列考量事項：

* 一般而言、您不應一次關閉多個節點、以免發生中斷。
* 除非文件或技術支援明確指示、否則請勿在維護程序期間關閉節點。
* 關機程序取決於節點的安裝位置、如下所示：
+
** 關閉VMware節點會關閉虛擬機器。
** 關閉Linux節點會關閉容器。
** 關閉StorageGRID 一個不中斷的應用程式節點會關閉運算控制器。


* 如果您打算在站台上關閉多個儲存節點、請在關閉節點之前、先停止在該站台上擷取物件約一小時。
+
如果有任何 ILM 規則使用 * 雙重認可 * 擷取選項（或如果規則使用 * 平衡 * 選項、且無法立即建立所有必要的複本）、 StorageGRID 會立即將任何新擷取的物件提交至同一站台上的兩個儲存節點、並於稍後評估 ILM 。如果站台上有多個儲存節點已關機、則在關機期間、您可能無法存取新擷取的物件。如果站台上的儲存節點數量太少、寫入作業也可能會失敗。請參閱 link:../ilm/index.html["使用ILM管理物件"]。



.步驟
. 登入網格節點：
+
.. 輸入下列命令： `ssh admin@_grid_node_IP_`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：
.. 輸入下列命令以切換至root： `su -`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：


+
當您以root登入時、提示會從變更 `$` 至 `#`。

. 停止所有服務： `service servermanager stop`
+
服務關機最多需要15分鐘、您可能想要從遠端登入系統、以監控關機程序。

. 如果節點是在VMware虛擬機器上執行、或是在應用裝置節點上執行、請發出關機命令： `shutdown -h now`
+
執行此步驟時、無論結果為何 `service servermanager stop` 命令。

+

NOTE: 在您發行之後 `shutdown -h now` 在應用裝置節點上執行命令時、您必須重新啟動應用裝置電源、才能重新啟動節點。

+
對於應用裝置、此命令會關閉控制器、但應用裝置仍會開啟電源。您必須完成下一步。

. 如果您要關閉應用裝置節點的電源、請遵循應用裝置的步驟。
+
[role="tabbed-block"]
====
.SGF6112
--
.. 關閉產品電源。
.. 等待藍色電源LED燈關閉。


--
.SG6000
--
.. 等待儲存控制器背面的綠色快取作用中LED關閉。
+
當需要將快取的資料寫入磁碟機時、此LED會亮起。您必須等待此LED燈關閉、才能關閉電源。

.. 關閉產品電源、然後等待藍色電源LED燈關閉。


--
.SG5700
--
.. 等待儲存控制器背面的綠色快取作用中LED關閉。
+
當需要將快取的資料寫入磁碟機時、此LED會亮起。您必須等待此LED燈關閉、才能關閉電源。

.. 關閉產品電源、並等待所有LED和七段顯示活動停止。


--
.SG100 或 SG1000
--
.. 關閉產品電源。
.. 等待藍色電源LED燈關閉。


--
====

