---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: 儲存節點可管理及儲存物件資料和中繼資料。儲存節點包括在磁碟上儲存、移動、驗證及擷取物件資料和中繼資料所需的服務和程序。 
---
= 什麼是儲存節點？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存節點可管理及儲存物件資料和中繼資料。儲存節點包括在磁碟上儲存、移動、驗證及擷取物件資料和中繼資料所需的服務和程序。

StorageGRID 系統中的每個站台必須至少有三個儲存節點。



== 儲存節點類型

在 StorageGRID 11.8 之前安裝的所有儲存節點都會儲存這些物件的物件和中繼資料。從 StorageGRID 11.8 開始、您可以為新的軟體型儲存節點選擇儲存節點類型：

物件和中繼資料儲存節點:: 根據預設、安裝在 StorageGRID 11.8 中的所有新儲存節點都會同時儲存物件和中繼資料。
純中繼資料儲存節點（僅限軟體型節點）:: 您可以指定新的軟體型儲存節點僅用於儲存中繼資料。您也可以在 StorageGRID 系統擴充期間、將純中繼資料軟體型儲存節點新增至 StorageGRID 系統。
+
--

NOTE: 您只能在初次安裝軟體型節點時、或在 StorageGRID 系統擴充期間安裝軟體型節點時、選取儲存節點類型。節點安裝完成後、您無法變更類型。

--


通常不需要安裝純中繼資料節點。不過、如果您的網格儲存了大量的小型物件、則只使用儲存節點來儲存中繼資料是很有意義的。安裝專用中繼資料容量可在大量小型物件所需的空間與所有這些物件的中繼資料所需空間之間取得更好的平衡。

軟體型中繼資料專用節點資源必須符合現有的儲存節點資源。例如：

* 如果現有的 StorageGRID 站台使用 SG6000 或 SG6100 應用裝置，則僅限軟體型中繼資料節點必須符合下列最低需求：
+
** 128 GB RAM
** 8 核心 CPU
** 8 TB SSD 或與 Cassandra 資料庫相同的儲存設備（ rangedb/0 ）


* 如果現有的 StorageGRID 站台使用具有 24 GB RAM ， 8 核心 CPU 和 3 TB 或 4TB 中繼資料儲存設備的虛擬儲存節點，則僅軟體中繼資料節點應使用類似資源（ 24 GB RAM ， 8 核心 CPU 和 4TB 中繼資料儲存設備（ rangedb/0 ）。


新增 StorageGRID 站台時，新站台的中繼資料總容量至少應與現有的 StorageGRID 站台和新站台資源相符，且應與現有 StorageGRID 站台的儲存節點相符。

在安裝具有僅軟體中繼資料節點的網格時、網格也必須包含物件儲存的最少節點數：

* 對於單一站台網格、至少會針對物件和中繼資料設定兩個儲存節點。
* 對於多站台網格、每個站台至少要設定一個儲存節點、用於物件和中繼資料。


軟體型儲存節點會在列出儲存節點類型的所有頁面上、針對每個僅中繼資料節點顯示僅中繼資料指示。



== 儲存節點的主要服務

下表顯示儲存節點的主要服務、但此表並未列出所有節點服務。


NOTE: 有些服務（例如、ADC服務和RSM服務）通常只存在於每個站台的三個儲存節點上。

[cols="1a,3a"]
|===
| 服務 | 按鍵功能 


 a| 
帳戶（帳戶）
 a| 
管理租戶帳戶。



 a| 
管理網域控制器（ADC）
 a| 
維護拓撲和整個網格的組態。

.詳細資料
[%collapsible]
====
管理網域控制器（ADC）服務會驗證網格節點及其彼此的連線。ADC 服務至少託管在一個站台的三個儲存節點上。

ADC服務負責維護拓撲資訊、包括服務的位置和可用度。當網格節點需要來自另一個網格節點的資訊、或是由另一個網格節點執行的動作時、它會聯絡某個ADC服務、以尋找處理其要求的最佳網格節點。此外、 ADC 服務會保留 StorageGRID 部署組態套件的複本、讓任何網格節點都能擷取目前的組態資訊。

為了方便分散式和分散式作業、每個ADC服務都會將憑證、組態套件、服務和拓撲的相關資訊、與StorageGRID 其他的子系統中的ADC服務進行同步。

一般而言、所有網格節點都會維持至少一項ADC服務的連線。如此可確保網格節點永遠存取最新資訊。當網格節點連線時、它們會快取其他網格節點的憑證、即使 ADC 服務無法使用、系統仍能繼續使用已知網格節點運作。新的網格節點只能使用ADC服務建立連線。

每個網格節點的連線可讓ADC服務收集拓撲資訊。此網格節點資訊包括CPU負載、可用磁碟空間（如果有儲存設備）、支援的服務、以及網格節點的站台ID。其他服務則透過拓撲查詢、要求ADC服務提供拓撲資訊。ADC服務會回應每個查詢、並提供StorageGRID 從該系統接收到的最新資訊。

====


 a| 
Cassandra
 a| 
儲存及保護物件中繼資料。



 a| 
Cassandra Reaper
 a| 
自動修復物件中繼資料。



 a| 
區塊
 a| 
管理銷毀編碼的資料和同位元檢查片段。



 a| 
資料移轉（DMV）
 a| 
將資料移至雲端儲存資源池。



 a| 
分散式資料儲存區（DDS）
 a| 
監控物件中繼資料儲存。

.詳細資料
[%collapsible]
====
每個儲存節點都包含分散式資料儲存區（ DDS ）服務。此服務會與 Cassandra 資料庫進行介面、以對儲存在 StorageGRID 系統中的物件中繼資料執行背景工作。

DDS服務會追蹤擷取至StorageGRID 該系統的物件總數、以及透過每個系統支援的介面（S3或Swift）擷取的物件總數。

====


 a| 
身分識別（idnt）
 a| 
聯盟LDAP和Active Directory的使用者身分識別。



 a| 
本機發佈路由器（LDR）
 a| 
處理物件儲存傳輸協定要求、並管理磁碟上的物件資料。

.詳細資料
[%collapsible]
====
每個儲存節點都包含本機配送路由器（ LDR ）服務。此服務可處理內容傳輸功能、包括資料儲存、路由和要求處理。LDR 服務可處理資料傳輸負載和資料傳輸功能、以完成 StorageGRID 系統的大部分工作。

LDR服務負責下列工作：

* 查詢
* 資訊生命週期管理（ILM）活動
* 物件刪除
* 物件資料儲存
* 從另一個LDR服務（儲存節點）傳輸物件資料
* 資料儲存管理
* 傳輸協定介面（S3和Swift）


LDR 服務也會將每個 S3 和 Swift 物件對應至其唯一 UUID 。

物件存放區:: LDR服務的基礎資料儲存區分為固定數量的物件存放區（也稱為儲存磁碟區）。每個物件存放區都是個別的掛載點。
+
--
儲存節點中的物件會以介於0000到002F之間的十六進位數字來識別、這稱為Volume ID。空間會保留在第一個物件存放區（Volume 0）中、以供Cassandra資料庫中的物件中繼資料使用；該磁碟區上的任何剩餘空間都會用於物件資料。所有其他物件存放區僅用於物件資料、包括複寫複本和銷毀編碼的片段。

為了確保複寫複本的空間使用率、會根據可用的儲存空間、將特定物件的物件資料儲存至單一物件存放區。物件儲存區填滿容量時、其餘物件儲存區會繼續儲存物件、直到儲存節點上沒有空間為止。

--
中繼資料保護:: 將物件中繼資料儲存在Cassandra資料庫中、該資料庫與LDR服務介面。StorageGRID
+
--
為了確保備援並保護資料免於遺失、每個站台都會保留三份物件中繼資料複本。此複寫無法設定、而且會自動執行。如需詳細資訊、請參閱 link:../admin/managing-object-metadata-storage.html["管理物件中繼資料儲存"]。

--


====


 a| 
複寫狀態機器（RSM）
 a| 
確保 S3 平台服務要求會傳送至各自的端點。



 a| 
伺服器狀態監視器（SSM）
 a| 
監控作業系統和基礎硬體。

|===