---
permalink: ilm/creating-cloud-storage-pool.html 
sidebar: sidebar 
keywords: how to create cloud storage pool 
summary: Cloud Storage Pool 會指定單一外部 Amazon S3 儲存區或其他 S3 相容提供者、或 Azure Blob 儲存容器。 
---
= 建立雲端儲存資源池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cloud Storage Pool 會指定單一外部 Amazon S3 儲存區或其他 S3 相容提供者、或 Azure Blob 儲存容器。

建立雲端儲存池時、您可以指定 StorageGRID 用來儲存物件的外部儲存區或容器名稱和位置、雲端供應商類型（ Amazon S3/GCP 或 Azure Blob 儲存設備）、以及 StorageGRID 存取外部儲存區或容器所需的資訊。

一旦儲存雲端儲存資源池、即可驗證其運作、因此您必須確保Cloud Storage Pool中指定的儲存庫或容器存在且可存取。StorageGRID

.開始之前
* 您將使用登入Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
* 您擁有 link:../admin/admin-group-permissions.html["必要的存取權限"]。
* 您已檢閱 link:considerations-for-cloud-storage-pools.html["雲端儲存資源池的考量"]。
* Cloud Storage Pool 所參照的外部儲存區或容器已經存在、您知道其名稱和位置。
* 若要存取貯體或容器、您可以針對您要選擇的驗證類型、提供下列資訊：
+
[role="tabbed-block"]
====
.S3 存取金鑰
--
_ 適用於外部 S3 儲存庫 _

** 擁有外部儲存庫之帳戶的存取金鑰 ID 。
** 相關的秘密存取金鑰。


或者、您也可以為驗證類型指定「匿名」。

--
.C2S 存取入口網站
--
商業雲端服務（ C2S ） S3 服務 _

您有下列項目：

** 完整的 URL 、 StorageGRID 將用來從 C2S 存取入口網站（ CAP ）伺服器取得臨時認證、包括指派給您 C2S 帳戶的所有必要和選用 API 參數。
** 由適當的政府憑證授權單位（ CA ）所核發的伺服器 CA 憑證。此憑證可用來驗證CAP伺服器的身分。StorageGRID伺服器CA憑證必須使用PEE編碼。
** 由適當的政府憑證授權單位（ CA ）所核發的用戶端憑證。此憑證可用於將自己的身分識別至CAP伺服器。StorageGRID用戶端憑證必須使用PEE編碼、而且必須已獲得存取您的C2S帳戶的權限。
** 用戶端憑證的 PEM 編碼私密金鑰。
** 用於解密用戶端憑證私密金鑰的複雜密碼（如果已加密）。



NOTE: 如果要加密用戶端憑證、請使用傳統的加密格式。不支援 PKCS #8 加密格式。

--
.Azure Blob 儲存設備
--
外部容器 _

** 用於存取 Blob 儲存容器的統一資源識別元（ URI ）。
** 儲存帳戶名稱和帳戶金鑰。您可以使用Azure入口網站來尋找這些價值。


--
====


.步驟
. 選取 * ILM * > * 儲存池 * > * 雲端儲存池 * 。
. 選取 * 建立 * 、然後輸入下列資訊：
+
[cols="1a,3a"]
|===
| 欄位 | 說明 


 a| 
雲端儲存池名稱
 a| 
簡短說明雲端儲存資源池及其用途的名稱。設定ILM規則時、請使用容易識別的名稱。



 a| 
供應商類型
 a| 
您將使用哪家雲端供應商來管理此雲端儲存資源池：

** * Amazon S3/GCP* ：針對 Amazon S3 、商業雲端服務（ C2S ） S3 、 Google Cloud Platform （ GCP ）或其他相容 S3 的供應商、選取此選項。
** * Azure Blob Storage *




 a| 
貯體或容器
 a| 
外部 S3 貯體或 Azure 容器的名稱。您無法在儲存雲端儲存池後變更此值。

|===
. 根據您的供應商類型選擇、輸入服務端點資訊。
+
[role="tabbed-block"]
====
.Amazon S3/GCP
--
.. 對於通訊協定、請選取 HTTPS 或 HTTP 。
+

NOTE: 請勿將 HTTP 連線用於敏感資料。

.. 輸入主機名稱。範例：
+
`s3-_aws-region_.amazonaws.com`

.. 選取 URL 樣式：
+
[cols="1a,3a"]
|===
| 選項 | 說明 


 a| 
自動偵測
 a| 
根據所提供的資訊、嘗試自動偵測要使用的URL樣式。例如、如果您指定IP位址、StorageGRID 則表示功能表將使用路徑樣式URL。僅當您不知道要使用哪種特定樣式時、才選取此選項。



 a| 
虛擬代管風格
 a| 
使用虛擬託管型 URL 來存取貯體。虛擬託管型 URL 會將貯體名稱納入網域名稱中。範例： `+https://bucket-name.s3.company.com/key-name+`



 a| 
路徑樣式
 a| 
使用路徑樣式URL存取儲存區。路徑樣式的 URL 結尾包含貯體名稱範例： `+https://s3.company.com/bucket-name/key-name+`

* 附註： * 不建議使用路徑樣式的 URL 選項、而且在未來的 StorageGRID 版本中將會被淘汰。

|===
.. 您也可以輸入連接埠編號、或使用預設連接埠： 443 代表 HTTPS 、 80 代表 HTTP 。


--
.Azure Blob儲存設備
--
.. 使用下列其中一種格式、輸入服務端點的 URI 。
+
*** `+https://host:port+`
*** `+http://host:port+`




範例： `https://_myaccount_.blob.core.windows.net:443`

如果您未指定連接埠、則預設會使用連接埠 443 做為 HTTPS 、並使用連接埠 80 做為 HTTP 。

--
====


. 選擇*繼續*。然後選取驗證類型、並輸入 Cloud Storage Pool 端點所需的資訊：
+
[role="tabbed-block"]
====
.存取金鑰
--
_ 僅適用於 Amazon S3/GCP 供應商類型 _

.. 對於 * 存取金鑰 ID* 、請輸入擁有外部儲存庫之帳戶的存取金鑰 ID 。
.. 對於 * 秘密存取金鑰 * 、請輸入秘密存取金鑰。


--
.CAP （ C2S 存取入口網站）
--
商業雲端服務（ C2S ） S3 服務 _

.. 對於 * 暫存認證 URL* 、請輸入 StorageGRID 從 CAP 伺服器取得暫存認證所使用的完整 URL 、包括指派給您的 C2S 帳戶的所有必要和選用 API 參數。
.. 對於 * 伺服器 CA 憑證 * 、請選取 * 瀏覽 * 、然後上傳 StorageGRID 用來驗證 CAP 伺服器的 PEM 編碼 CA 憑證。
.. 對於 * 用戶端憑證 * 、請選取 * 瀏覽 * 、然後上傳 StorageGRID 用來識別自身的 PEM 編碼憑證至 CAP 伺服器。
.. 對於 * 用戶端私密金鑰 * 、請選取 * 瀏覽 * 、然後上傳用戶端憑證的 PEM 編碼私密金鑰。
.. 如果用戶端私密金鑰已加密、請輸入密碼來解密用戶端私密金鑰。否則、請將 * 用戶端私密金鑰複雜密碼 * 欄位保留空白。


--
.Azure Blob儲存設備
--
.. 對於 * 帳戶名稱 * 、請輸入擁有外部服務容器的 Blob 儲存帳戶名稱。
.. 對於 * 帳戶金鑰 * 、請輸入 Blob 儲存帳戶的秘密金鑰。


--
.匿名
--
不需要其他資訊。

--
====
. 選擇*繼續*。然後選擇您要使用的伺服器驗證類型：
+
[cols="1a,2a"]
|===
| 選項 | 說明 


 a| 
在儲存節點作業系統中使用根 CA 憑證
 a| 
使用安裝在作業系統上的Grid CA憑證來保護連線安全。



 a| 
使用自訂CA憑證
 a| 
使用自訂CA憑證。選取 * 瀏覽 * 、然後上傳 PEM 編碼的憑證。



 a| 
請勿驗證憑證
 a| 
用於TLS連線的憑證尚未驗證。

|===
. 選擇*保存*。
+
當您儲存雲端儲存資源池時StorageGRID 、下列功能將會隨之執行：

+
** 驗證貯體或容器及服務端點是否存在、以及是否可使用您指定的認證來連線。
** 將標記檔案寫入貯體或容器、以將其識別為雲端儲存池。請勿移除此檔案、其名稱為 `x-ntap-sgws-cloud-pool-uuid`。
+
如果Cloud Storage Pool驗證失敗、您會收到錯誤訊息、說明驗證失敗的原因。例如、如果發生憑證錯誤、或是您指定的貯體或容器尚未存在、則可能會回報錯誤。



. 如果發生錯誤、請參閱 link:troubleshooting-cloud-storage-pools.html["疑難排解雲端儲存資源池的指示"]、解決任何問題、然後再次嘗試儲存雲端儲存池。

