---
permalink: ilm/troubleshooting-cloud-storage-pools.html 
sidebar: sidebar 
keywords: cloud storage pool, troubleshoot 
summary: 使用這些疑難排解步驟、協助解決您在建立、編輯或刪除雲端儲存池時可能遇到的錯誤。 
---
= 疑難排解雲端儲存資源池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用這些疑難排解步驟、協助解決您在建立、編輯或刪除雲端儲存池時可能遇到的錯誤。



== 確定是否發生錯誤

每分鐘執行一次簡易的Cloud Storage Pool健全狀況檢查、以確保雲端儲存池能夠存取、而且運作正常。StorageGRID如果健全狀況檢查偵測到問題、「儲存池」頁面上的「雲端儲存池」表最後一個錯誤欄會顯示訊息。

下表顯示針對每個雲端儲存資源池偵測到的最新錯誤、並指出錯誤發生的時間已過多久。

此外、如果健全狀況檢查偵測到過去5分鐘內發生一或多個新的雲端儲存池錯誤、則會觸發* Cloud Storage Pool連線錯誤*警示。如果您收到此警示的電子郵件通知、請前往「儲存資源池」頁面（選擇 * ILM * > * 儲存資源池 * ）、檢閱最後一個錯誤欄中的錯誤訊息、並參閱下列疑難排解準則。



== 檢查錯誤是否已解決

解決任何潛在問題之後、您可以判斷錯誤是否已解決。從「雲端儲存池」頁面選取端點、然後選取 * 清除錯誤 * 。確認訊息指出StorageGRID 、由於此錯誤已清除Cloud Storage Pool的錯誤。

如果基礎問題已解決、就不會再顯示錯誤訊息。但是、如果基礎問題尚未解決（或遇到不同的錯誤）、則錯誤訊息會在幾分鐘內顯示在最後一個錯誤欄中。



== 錯誤：此Cloud Storage Pool包含非預期的內容

當您嘗試建立、編輯或刪除雲端儲存池時、可能會遇到此錯誤。如果儲存區或容器包含、就會發生此錯誤 `x-ntap-sgws-cloud-pool-uuid` 標記檔案、但該檔案沒有預期的UUID。

一般而StorageGRID 言、如果您正在建立新的Cloud Storage Pool、而另一個執行個體正在使用相同的Cloud Storage Pool、則只會看到此錯誤。

請嘗試下列步驟來修正問題：

* 請確認貴組織中沒有人也使用此雲端儲存資源池。
* 刪除 `x-ntap-sgws-cloud-pool-uuid` 重新設定雲端儲存資源池。




== 錯誤：無法建立或更新雲端儲存池。端點發生錯誤

當您嘗試建立或編輯雲端儲存資源池時、可能會遇到此錯誤。此錯誤表示某種連線或組態問題阻礙StorageGRID 了將資訊寫入Cloud Storage Pool。

若要修正問題、請檢閱端點的錯誤訊息。

* 如果錯誤訊息包含 `Get _url_: EOF`、請檢查雲端儲存池所使用的服務端點、是否不針對需要 HTTPS 的容器或貯體使用 HTTP 。
* 如果錯誤訊息包含 `Get _url_: net/http: request canceled while waiting for connection`、確認網路組態允許儲存節點存取用於雲端儲存資源池的服務端點。
* 對於所有其他端點錯誤訊息、請嘗試下列其中一項或多項：
+
** 建立與您為Cloud Storage Pool輸入相同名稱的外部容器或儲存區、然後再次嘗試儲存新的Cloud Storage Pool。
** 請更正您為Cloud Storage Pool指定的容器或儲存區名稱、然後再次嘗試儲存新的Cloud Storage Pool。






== 錯誤：無法剖析CA憑證

當您嘗試建立或編輯雲端儲存資源池時、可能會遇到此錯誤。如果在設定Cloud Storage Pool時、無法剖析您輸入的憑證、就會發生錯誤StorageGRID 。

若要修正問題、請檢查您提供的CA憑證是否有問題。



== 錯誤：找不到具有此ID的雲端儲存資源池

當您嘗試編輯或刪除雲端儲存資源池時、可能會遇到此錯誤。如果端點傳回404回應、就會發生此錯誤、這可能代表下列其中一項：

* 雲端儲存池使用的認證資料沒有儲存區的讀取權限。
* 用於雲端儲存資源池的儲存區不含 `x-ntap-sgws-cloud-pool-uuid` 標記檔案。


請嘗試下列一或多個步驟來修正問題：

* 檢查與設定的存取金鑰相關聯的使用者是否擁有必要的權限。
* 使用具備必要權限的認證資料編輯Cloud Storage Pool。
* 如果權限正確、請聯絡支援部門。




== 錯誤：無法檢查Cloud Storage Pool的內容。端點發生錯誤

當您嘗試刪除雲端儲存資源池時、可能會遇到此錯誤。此錯誤表示某種連線或組態問題使StorageGRID 無法讀取Cloud Storage Pool儲存區儲存區內容。

若要修正問題、請檢閱端點的錯誤訊息。



== 錯誤：物件已放置在此儲存區中

當您嘗試刪除雲端儲存資源池時、可能會遇到此錯誤。如果雲端儲存池包含由 ILM 移至該處的資料、設定雲端儲存池之前儲存在儲存區中的資料、或是建立雲端儲存池之後由其他來源放入儲存區的資料、則您無法刪除該儲存池。

請嘗試下列一或多個步驟來修正問題：

* 請依照「雲端儲存池物件生命週期」中的指示、將物件移回 StorageGRID 。
* 如果您確定其餘的物件並非由ILM放置在雲端儲存資源池中、請手動刪除儲存區中的物件。
+

NOTE: 切勿手動刪除ILM可能放置在雲端儲存資源池中的物件。如果您稍後嘗試從StorageGRID 功能表存取手動刪除的物件、將無法找到刪除的物件。





== 錯誤：Proxy嘗試連至雲端儲存資源池時發生外部錯誤

如果您已在儲存節點和用於雲端儲存池的外部 S3 端點之間設定不透明儲存 Proxy 、則可能會遇到此錯誤。如果外部 Proxy 伺服器無法連線至雲端儲存池端點、就會發生此錯誤。例如、DNS伺服器可能無法解析主機名稱、或是發生外部網路問題。

請嘗試下列一或多個步驟來修正問題：

* 檢查雲端儲存資源池的設定（* ILM *>* Storage Pools*）。
* 檢查儲存 Proxy 伺服器的網路組態。


.相關資訊
link:lifecycle-of-cloud-storage-pool-object.html["Cloud Storage Pool物件的生命週期"]
